// questions/p1.js — 제1편 가구와 목공에 설계
// id 규칙: 10xx (1001, 1002, ...)
window.QUESTIONS = (window.QUESTIONS || []).concat([
  { id: 1001, subject: "제1편 가구와 목공에 설계", question: "디바이더의 사용법 중 틀린 것은?", image: "", options: ["치수를 도면에 옮길 때", "작은 원을 그릴 때", "선을 일정한 간격으로 분할할 때", "도면의 길이를 다른 도면에 옮길 때"], answer: 2, explanation: "" },
  { id: 1002, subject: "제1편 가구와 목공에 설계", question: "컴퍼스를 사용하여 원을 그리는 방향은?", image: "", options: ["시계 방향", "반시계 방향", "앞 오른쪽에서 시계 반대 방향", "방향에 무관"], answer: 1, explanation: "" },
  { id: 1003, subject: "제1편 가구와 목공에 설계", question: "축척 눈금을 제도용지에 옮기거나 도면 위의 선을 등분할 때 사용하는 제도 용구는?", image: "", options: ["빔 컴퍼스", "디바이더", "삼각자", "먹줄펜"], answer: 2, explanation: "" },
  { id: 1004, subject: "제1편 가구와 목공에 설계", question: "가장 큰 원을 그릴 수 있는 컴퍼스는?", image: "", options: ["대형 컴퍼스", "중형 컴퍼스", "빔 컴퍼스", "스프링 컴퍼스"], answer: 3, explanation: "" },
  { id: 1005, subject: "제1편 가구와 목공에 설계", question: "먹줄펜의 종류에 속하지 않는 것은?", image: "", options: ["보통 먹줄펜", "점선 먹줄펜", "양머리 곡선 먹줄펜", "채석 먹줄펜"], answer: 4, explanation: "" },
  { id: 1006, subject: "제1편 가구와 목공에 설계", question: "다음 중 디바이더를 사용하기에 적합한 경우는?", image: "", options: ["직선을 그을 때", "선을 등분할 때", "줄여서 그릴 때", "곡선을 그릴 때"], answer: 2, explanation: "" },
  { id: 1007, subject: "제1편 가구와 목공에 설계", question: "그림에서 각 A는 몇 도인가?", image: "", options: ["15°", "30°", "45°", "60°"], answer: 1, explanation: "" },
  { id: 1008, subject: "제1편 가구와 목공에 설계", question: "여러 가지 곡선을 자유롭게 그릴 때 사용하는 제도 용구로, 납과 고무로 만들어져 자유롭게 구부릴 수 있는 것은?", image: "", options: ["운형자", "축척자", "형판", "자유곡선자"], answer: 4, explanation: "" },
  { id: 1009, subject: "제1편 가구와 목공에 설계", question: "삼각스케일에 대한 설명으로 틀린 것은?", image: "", options: ["임의의 축척으로 도면을 그릴 때 사용한다.", "1/100, 1/200, 1/300, 1/400, 1/500, 1/600의 6가지 축척 눈금이 있다.", "1/10, 1/20, 1/30 등의 도면을 작도할 때도 사용한다.", "길이를 재거나 길이를 줄여 그릴 때 사용한다."], answer: 1, explanation: "" },
  { id: 1010, subject: "제1편 가구와 목공에 설계", question: "축척자(scale ruler)의 축척 눈금에 해당하지 않는 것은?", image: "", options: ["1/300", "1/500", "1/600", "1/700"], answer: 4, explanation: "" },
  { id: 1011, subject: "제1편 가구와 목공에 설계", question: "삼각자의 크기는 어느 부분을 기준으로 하는가?", image: "", options: ["45° 자의 빗변과 60° 자의 수선 길이", "45° 자의 빗변과 60° 자의 빗변 길이", "45° 자의 수선 길이와 60° 자의 빗변 길이", "45° 자의 수선 길이와 60° 자의 수선 길이"], answer: 1, explanation: "" },
  { id: 1012, subject: "제1편 가구와 목공에 설계", question: "T자와 삼각자의 사용법에 대하여 바르게 설명한 것은?", image: "", options: ["수평선은 우측에서 좌측으로 선을 긋는다.", "수직선은 위에서 아래로 긋는다.", "경사선은 T자를 경사로 놓고 긋는다.", "수평선과 수직선을 긋는 데 사용한다."], answer: 4, explanation: "" },
  { id: 1013, subject: "제1편 가구와 목공에 설계", question: "다음 중 디바이더의 용도가 아닌 것은?", image: "", options: ["제도용지에 호를 그린다.", "직선을 일정한 치수로 나눈다.", "도면 위의 길이를 재어 다른 곳에 옮긴다.", "원둘레를 등분한다."], answer: 1, explanation: "" },
  { id: 1014, subject: "제1편 가구와 목공에 설계", question: "다음과 같은 그림을 그리기 위한 제도 용구가 아닌 것은?", image: "", options: ["T자", "삼각자", "운형자", "디바이더"], answer: 4, explanation: "" },
  { id: 1015, subject: "제1편 가구와 목공에 설계", question: "다음 연필 중 경도가 가장 낮은 것은?", image: "", options: ["H", "F", "HB", "B"], answer: 4, explanation: "" },
  { id: 1016, subject: "제1편 가구와 목공에 설계", question: "제도판에 있어서 중판의 규격으로 알맞은 것은?", image: "", options: ["600×450mm", "900×600mm", "1000×750mm", "1200×900mm"], answer: 2, explanation: "" },
  { id: 1017, subject: "제1편 가구와 목공에 설계", question: "합판으로 만든 제도판의 올거미 재료로 적합하지 않은 것은?", image: "", options: ["춘양목", "나왕", "벚나무", "낙엽송"], answer: 4, explanation: "" },
  { id: 1018, subject: "제1편 가구와 목공에 설계", question: "제도판에 대한 설명으로 옳지 않은 것은?", image: "", options: ["뒤틀림이 없어야 한다.", "두께는 두꺼울수록 좋다.", "표면이 평평해야 한다.", "크기는 특대판, 대판, 중판, 소판으로 구분한다."], answer: 2, explanation: "" },
  { id: 1019, subject: "제1편 가구와 목공에 설계", question: "다음 중 만능 제도기의 기능에 해당하지 않는 것은?", image: "", options: ["삼각자 기능", "T자 기능", "운형자 기능", "각도기 기능"], answer: 3, explanation: "" },
  { id: 1020, subject: "제1편 가구와 목공에 설계", question: "직선 A, B에서 점 B에 수선을 긋는 방법으로 옳지 않은 것은?", image: "", options: ["CB = CD", "CD = DE", "DF = EF", "BG = FG"], answer: 4, explanation: "" },
  { id: 1021, subject: "제1편 가구와 목공에 설계", question: "다음 그림과 같이 주어진 직선 AB를 수직 2등분할 때 옳지 않은 것은?", image: "", options: ["AE = BE", "AC = BC", "AE = CE", "CD ⊥ AB"], answer: 3, explanation: "" },
  { id: 1022, subject: "제1편 가구와 목공에 설계", question: "선분 AB를 다음 그림과 같이 나타낸 것은 어떤 기하학적 원리를 의미하는가?", image: "", options: ["평행", "대칭", "합동", "균형"], answer: 1, explanation: "" },
  { id: 1023, subject: "제1편 가구와 목공에 설계", question: "다음은 직각을 3등분한 그림이다. 길이에 관한 설명으로 틀린 것은?", image: "", options: ["AD = DC", "OA = AD", "AD = BC", "DC = BC"], answer: 2, explanation: "" },
  { id: 1024, subject: "제1편 가구와 목공에 설계", question: "직사각형과 같은 넓이의 정사각형 그리기에서 옳은 것은?", image: "", options: ["DF = FE", "BC = CG", "CE = CG", "DF = FH"], answer: 1, explanation: "" },
  { id: 1025, subject: "제1편 가구와 목공에 설계", question: "원과 같은 넓이의 정사각형을 작도할 때, 각각 어느 점을 중심으로 하여 AB를 반지름으로 호를 그리면 되는가?", image: "", options: ["A, B", "C, D", "E, F", "B, D"], answer: 4, explanation: "" },
  { id: 1026, subject: "제1편 가구와 목공에 설계", question: "원의 반지름으로 원주를 끊고, 그 끊은 점과 점을 연결하여 만들어진 원에 접하는 다각형은?", image: "", options: ["정사각형", "정오각형", "정육각형", "정팔각형"], answer: 3, explanation: "" },
  { id: 1027, subject: "제1편 가구와 목공에 설계", question: "원에 내접하는 정오각형을 그리는 방법이 아닌 것은?", image: "", options: ["AO ⊥ KL", "OM = ML", "AM = MN", "AM = AB"], answer: 4, explanation: "" },
  { id: 1028, subject: "제1편 가구와 목공에 설계", question: "한 변이 주어진 정오각형 작도 그림에서 DE의 길이는?", image: "", options: ["AD/2", "AD/3", "AB/2", "CF/4"], answer: 3, explanation: "" },
  { id: 1029, subject: "제1편 가구와 목공에 설계", question: "다음은 AB를 한 변으로 하는 정육각형을 그리는 작도이다. 순서상 가장 먼저 구해야 할 점은?", image: "", options: ["C", "O", "D", "E"], answer: 2, explanation: "" },
  { id: 1030, subject: "제1편 가구와 목공에 설계", question: "장축과 단축이 주어진 타원을 그릴 때의 작도 조건이 아닌 것은?", image: "", options: ["1/2 EF = G", "FH = OF", "AE = CO", "OE = OF"], answer: 2, explanation: "" },
  { id: 1031, subject: "제1편 가구와 목공에 설계", question: "다음 그림과 같은 표준 난형 작도에서 CE의 중심은?", image: "", options: ["A", "B", "C", "D"], answer: 4, explanation: "" },
  { id: 1032, subject: "제1편 가구와 목공에 설계", question: "단면 상세도를 그릴 때 표시하지 않아도 되는 것은?", image: "", options: ["각 실의 면적", "1층 바닥의 높이", "지붕 물매", "창의 높이"], answer: 1, explanation: "" },
  { id: 1033, subject: "제1편 가구와 목공에 설계", question: "평면도를 작도할 때 고려하지 않아도 되는 것은?", image: "", options: ["개구부의 위치와 크기", "실의 배치와 넓이", "기둥이나 벽의 위치", "처마 높이 및 지붕 재료"], answer: 4, explanation: "" },
  { id: 1034, subject: "제1편 가구와 목공에 설계", question: "건물의 외관을 나타내는 입면도 중 정면도를 가장 잘 표현한 것은?", image: "", options: ["개구부가 많이 있는 쪽", "복잡한 입면이 있는 쪽", "현관이 있는 쪽", "도로에 면한 쪽"], answer: 3, explanation: "" },
  { id: 1035, subject: "제1편 가구와 목공에 설계", question: "절단면의 실제 모양을 나타내는 도면은?", image: "", options: ["절단선", "보조 투상면", "단면도", "정투상도"], answer: 3, explanation: "" },
  { id: 1036, subject: "제1편 가구와 목공에 설계", question: "건축 도면에서 각 실의 크기, 위치 등을 표시하는 도면은?", image: "", options: ["평면도", "입면도", "단면도", "투시도"], answer: 1, explanation: "" },
  { id: 1037, subject: "제1편 가구와 목공에 설계", question: "건축 도면 중 바닥으로부터 1~1.5m 정도 윗부분을 수평으로 절단한 것을 상상하여 그린 것으로, 건축 도면의 기본이라 할 수 있는 것은?", image: "", options: ["평면도", "입면도", "부분 단면도", "투시도"], answer: 1, explanation: "" },
  { id: 1038, subject: "제1편 가구와 목공에 설계", question: "입체의 각 면을 한 면 위에 펴서 그린 도면을 무엇이라 하는가?", image: "", options: ["투시도", "상관체", "전개도", "음영도"], answer: 3, explanation: "" },
  { id: 1039, subject: "제1편 가구와 목공에 설계", question: "다음 그림과 같은 전개도의 입체는?", image: "", options: ["정사면체", "정사각뿔", "정삼각뿔", "삼각뿔"], answer: 3, explanation: "" },
  { id: 1040, subject: "제1편 가구와 목공에 설계", question: "정상각형으로만 구성되어 있는 입체는?", image: "", options: ["정사면체", "정육면체", "정십면체", "정십이면체"], answer: 1, explanation: "" },
  { id: 1041, subject: "제1편 가구와 목공에 설계", question: "도면에서 평면도, 배치도 등은 원칙적으로 어느 방향을 위로 하여 제도하는가?", image: "", options: ["동", "서", "남", "북"], answer: 4, explanation: "" },
  { id: 1042, subject: "제1편 가구와 목공에 설계", question: "다음 그림은 어떤 입체의 전개도인가?", image: "", options: ["정6각형", "정12면체", "정10면체", "정6면체"], answer: 2, explanation: "" },
  { id: 1043, subject: "제1편 가구와 목공에 설계", question: "다음 중 국제표준규격을 나타내는 것은?", image: "", options: ["ISO", "BS", "KS", "ASA"], answer: 1, explanation: "" },
  { id: 1044, subject: "제1편 가구와 목공에 설계", question: "건물 내부의 입면을 정면에서 바라보고 그리는 내부 입면도를 나타내는 것은?", image: "", options: ["투시도", "단면도", "전개도", "음영도"], answer: 3, explanation: "" },
  { id: 1045, subject: "제1편 가구와 목공에 설계", question: "도면 제작 시 도면에 반드시 마련해야 할 사항으로 짝지어진 것은?", image: "", options: ["도면의 윤곽, 표제란, 중심 마크", "도면의 윤곽, 표제란, 비교 눈금", "도면의 구역, 재단 마크, 비교 눈금", "도면의 구역, 재단 마크, 중심 마크"], answer: 1, explanation: "" },
  { id: 1046, subject: "제1편 가구와 목공에 설계", question: "도면에서 도면의 관리상 필요한 사항과 도면 내에 있는 내용에 관한 사항을 모아서 기입한 것은?", image: "", options: ["주서란", "요목표", "표제란", "부품란"], answer: 3, explanation: "" },
  { id: 1047, subject: "제1편 가구와 목공에 설계", question: "도면 관리에서 다른 도면과 구별하고, 도면 내용을 직접 보지 않고도 제품의 종류 및 형식 등 도면의 내용을 알 수 있게 하기 위해 기입하는 것은?", image: "", options: ["도면 번호", "도면 척도", "도면 양식", "부품 번호"], answer: 1, explanation: "" },
  { id: 1048, subject: "제1편 가구와 목공에 설계", question: "도면에 반드시 마련해야 하는 양식에 관한 설명 중 틀린 것은?", image: "", options: ["윤곽선은 도면의 크기에 따라 0.7mm 이상의 굵은 실선으로 그린다.", "표제란은 도면의 오른쪽 아래 구석에 그린다.", "도면을 마이크로필름으로 촬영하거나 복사할 때 편의를 위해서 중심 마크를 표시한다.", "부품란에는 도면 번호, 도면 명칭, 척도, 투상법 등을 기입한다."], answer: 4, explanation: "" },
  { id: 1049, subject: "제1편 가구와 목공에 설계", question: "도면에 마련하는 양식 중에서 마이크로필름 등으로 촬영하거나 복사 및 철할 때의 편의를 위해 마련하는 것은?", image: "", options: ["윤곽선", "표제란", "중심 마크", "구역 표시"], answer: 3, explanation: "" },
  { id: 1050, subject: "제1편 가구와 목공에 설계", question: "기계 제도 도면에 사용되는 척도의 설명이 틀린 것은?", image: "", options: ["도면에 그려지는 길이와 대상물의 실제 길이와의 비율로 나타낸다.", "한 도면에서 공통적으로 사용되는 척도는 표제란에 기입된다.", "같은 도면에서 다른 척도를 사용할 때는 필요에 따라 그림 근처에 기입한다.", "배척은 대상물보다 크게 그리는 것으로 2:1, 3:1, 4:1, 10:1 등 제도자 임의로 비율을 만들어 사용한다."], answer: 4, explanation: "" },
  { id: 1051, subject: "제1편 가구와 목공에 설계", question: "다음 그림과 같은 도면 양식에 관한 설명 중 틀린 것은?", image: "", options: ["ⓐ는 0.7mm 이상의 굵은 실선으로 긋고 도면의 윤곽을 나타내는 선이다.", "ⓑ는 0.7mm 이상의 굵은 실선으로 긋고 마이크로필름으로 촬영할 때 편의를 위해 사용한다.", "ⓒ는 도면에서 상세, 추가, 수정 등의 위치를 알기 쉽도록 용지를 여러 구역으로 나누는 데 사용된다.", "ⓓ는 표제란으로 척도, 투상법, 도면, 도명, 설계자, 기업명 등 도면에 관한 정보를 표시한다."], answer: 3, explanation: "" },
  { id: 1052, subject: "제1편 가구와 목공에 설계", question: "다음 중 부품란에 기입해야 할 사항이 아닌 것은?", image: "", options: ["품번", "품명", "재질", "투상법"], answer: 4, explanation: "" },
  { id: 1053, subject: "제1편 가구와 목공에 설계", question: "우선적으로 사용하는 배척의 종류가 아닌 것은?", image: "", options: ["50 : 1", "25 : 1", "5 : 1", "2 : 1"], answer: 2, explanation: "" },
  { id: 1054, subject: "제1편 가구와 목공에 설계", question: "도면을 그릴 때 척도 결정의 기준이 되는 것은 어느 것인가?", image: "", options: ["물체의 재질", "물체의 무게", "물체의 크기", "물체의 체적"], answer: 3, explanation: "" },
  { id: 1055, subject: "제1편 가구와 목공에 설계", question: "다음 중 현척의 의미는?", image: "", options: ["실물보다 축소하여 그린 것", "실물보다 확대하여 그린 것", "실물과 관계없이 그린 것", "실물과 같은 크기로 그린 것"], answer: 4, explanation: "" },
  { id: 1056, subject: "제1편 가구와 목공에 설계", question: "다음 축척의 종류 중 우선적으로 사용되는 척도가 아닌 것은?", image: "", options: ["1 : 2", "1 : 3", "1 : 5", "1 : 10"], answer: 2, explanation: "" },
  { id: 1057, subject: "제1편 가구와 목공에 설계", question: "다음 중 척도의 표시법 A : B의 설명으로 맞는 것은?", image: "", options: ["A는 물체의 실제 크기이다.", "B는 도면에서의 크기이다.", "배척일 때 B를 1로 나타낸다.", "현척일 때 A만을 1로 나타낸다."], answer: 3, explanation: "" },
  { id: 1058, subject: "제1편 가구와 목공에 설계", question: "도면의 표제란에 척도가 1 : 2로 기입되어 있다면 이 도면에서 사용된 척도의 종류로 알맞은 것은?", image: "", options: ["현척", "배척", "축척", "실척"], answer: 3, explanation: "" },
  { id: 1059, subject: "제1편 가구와 목공에 설계", question: "도면에서 100mm를 2 : 1 척도로 그릴 때 도면에 기입되는 치수는?", image: "", options: ["10", "200", "50", "100"], answer: 4, explanation: "" },
  { id: 1060, subject: "제1편 가구와 목공에 설계", question: "제도용지 전지를 그림과 같이 등분했을 때 빗금친 부분의 크기는?", image: "", options: ["A1", "A2", "A3", "A4"], answer: 2, explanation: "" },
  { id: 1061, subject: "제1편 가구와 목공에 설계", question: "도면에서 세로와 가로의 비는?", image: "", options: ["1 : √2", "1 : √3", "1 : √5", "1 : √8"], answer: 1, explanation: "" },
  { id: 1062, subject: "제1편 가구와 목공에 설계", question: "A0 제도용지의 크기는? 단, 단위는 mm", image: "", options: ["210×297", "297×420", "594×841", "841×1189"], answer: 4, explanation: "" },
  { id: 1063, subject: "제1편 가구와 목공에 설계", question: "도면을 접을 때 표준 크기로 옳은 것은?", image: "", options: ["A0", "A1", "A2", "A4"], answer: 4, explanation: "" },
  { id: 1064, subject: "제1편 가구와 목공에 설계", question: "도면을 접을 때 겉으로 드러나게 정리해야 하는 부분은?", image: "", options: ["조립도가 있는 부분", "표제란이 있는 부분", "재료표가 있는 부분", "부품도가 있는 부분"], answer: 2, explanation: "" },
  { id: 1065, subject: "제1편 가구와 목공에 설계", question: "도면에서 표제란이 위치하는 곳은 다음 중 어디인가?", image: "", options: ["도면의 오른쪽 위", "도면의 오른쪽 아래", "도면의 왼쪽 아래", "도면의 왼쪽 위"], answer: 2, explanation: "" },
  { id: 1066, subject: "제1편 가구와 목공에 설계", question: "다음 중 도면의 표제란에 표기하지 않아도 되는 것은?", image: "", options: ["재료 명칭", "도면 번호", "도면 이름", "작성 연월일"], answer: 1, explanation: "" },
  { id: 1067, subject: "제1편 가구와 목공에 설계", question: "제도를 할 때의 주의사항으로 옳지 않은 것은?", image: "", options: ["축척에 맞추어 그린 것이 아닐 때는 NS를 기입한다.", "도면은 제3각법으로 그리는 것을 원칙으로 한다.", "복잡한 부분의 제도에서는 실척을 사용할 수 있다.", "축척의 종류에는 3가지가 있다."], answer: 4, explanation: "" },
  { id: 1068, subject: "제1편 가구와 목공에 설계", question: "다음 중 축척의 척도는 어느 것인가?", image: "", options: ["1/2", "1/1", "2/1", "4/1"], answer: 1, explanation: "" },
  { id: 1069, subject: "제1편 가구와 목공에 설계", question: "500×100의 넓이를 가진 널빤지를 제작하기 위해 10 : 1의 비로 도면을 그렸다. 기입해야 할 치수는?", image: "", options: ["5×1", "50×10", "500×100", "5000×1000"], answer: 3, explanation: "" },
  { id: 1070, subject: "제1편 가구와 목공에 설계", question: "일정한 척도로 그리지 않아서 그림이 치수에 비례하지 않을 때 표제란에는 어떻게 표시하는가?", image: "", options: ["A : B", "NS", "0 : 0", "1 : 0"], answer: 2, explanation: "" },
  { id: 1071, subject: "제1편 가구와 목공에 설계", question: "실제 길이 32m를 축척 1/200으로 계산한 값은?", image: "", options: ["8cm", "12cm", "16cm", "64cm"], answer: 3, explanation: "" },
  { id: 1072, subject: "제1편 가구와 목공에 설계", question: "물체의 보이지 않는 부분의 모양을 표시하는 선은?", image: "", options: ["실선", "파선", "일점 쇄선", "선"], answer: 2, explanation: "" },
  { id: 1073, subject: "제1편 가구와 목공에 설계", question: "다음 중 해칭(hatching)선에 대한 설명으로 옳은 것은?", image: "", options: ["기본 중심선 또는 기선(분기선)에 대하여 30°의 가는 실선을 긋는다.", "같은 부품의 단면은 떨어져 있어도 해칭 방향과 간격을 같게 한다.", "서로 인접하는 단면의 해칭은 각도 및 간격을 같게 해서는 안 된다.", "해칭선은 45°의 굵은 직선을 사용한다."], answer: 2, explanation: "" },
  { id: 1074, subject: "제1편 가구와 목공에 설계", question: "다음 선의 명칭 중에서 가장 굵게 그려야 하는 것은?", image: "", options: ["단면선", "치수선", "절단선", "해칭선"], answer: 1, explanation: "" },
  { id: 1075, subject: "제1편 가구와 목공에 설계", question: "다음 파단선의 표시 기호 중 파단되어 있는 것이 명백할 때 나타낸 기호는?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 1, explanation: "" },
  { id: 1076, subject: "제1편 가구와 목공에 설계", question: "다음 중 트레이싱할 때 일반적으로 가장 먼저 긋는 선은?", image: "", options: ["치수선", "지시선", "파선", "수평선"], answer: 4, explanation: "" },
  { id: 1077, subject: "제1편 가구와 목공에 설계", question: "그림에서 선 A의 명칭으로 옳은 것은?", image: "", options: ["파단선", "단면선", "절단선", "가상선"], answer: 1, explanation: "" },
  { id: 1078, subject: "제1편 가구와 목공에 설계", question: "선의 용도에 따른 명칭 중 90° 정도 회전하는 물체를 회전시킨 후의 위치를 나타내는 선은?", image: "", options: ["외형선", "파단선", "가상선", "은선"], answer: 3, explanation: "" },
  { id: 1079, subject: "제1편 가구와 목공에 설계", question: "다음 중 실선의 용도로 알맞은 것은?", image: "", options: ["경계선", "숨은선", "상상선", "단면선"], answer: 4, explanation: "" },
  { id: 1080, subject: "제1편 가구와 목공에 설계", question: "도면에서 치수 보조선의 표시에 사용되는 선은?", image: "", options: ["파선", "굵은 실선", "1점 쇄선", "가는 실선"], answer: 4, explanation: "" },
  { id: 1081, subject: "제1편 가구와 목공에 설계", question: "단면의 윤곽을 나타내는 선으로 가장 알맞은 선은?", image: "", options: ["가는 실선", "파선", "이점 쇄선", "굵은 실선"], answer: 4, explanation: "" },
  { id: 1082, subject: "제1편 가구와 목공에 설계", question: "중심선, 절단선, 기준선, 경계선 등에 사용하는 선은?", image: "", options: ["실선", "파선", "1점 쇄선", "2점 쇄선"], answer: 3, explanation: "" },
  { id: 1083, subject: "제1편 가구와 목공에 설계", question: "가는 실선의 용도에 대한 설명으로 틀린 것은?", image: "", options: ["특수한 가공을 하는 부분을 나타낸다.", "인출선, 각도 설명 등을 나타내는 지시선으로 사용한다.", "도형의 중심을 표시한다.", "치수선으로 사용한다."], answer: 1, explanation: "" },
  { id: 1084, subject: "제1편 가구와 목공에 설계", question: "선을 긋는 방법으로 옳지 않은 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 3, explanation: "" },
  { id: 1085, subject: "제1편 가구와 목공에 설계", question: "그림에서 표시선 A가 나타내는 것은?", image: "", options: ["파단선", "경계선", "해칭선", "가상선"], answer: 3, explanation: "" },
  { id: 1086, subject: "제1편 가구와 목공에 설계", question: "제도에 사용되는 선에 대한 설명 중 옳지 않은 것은?", image: "", options: ["실선은 물체의 보이는 부분을 나타내는 데 사용한다.", "파선은 물체의 보이지 않는 부분의 모양을 표시하는 데 사용한다.", "중심선은 물체의 중심축, 대칭축을 표시하는 데 사용한다.", "절단선은 물체가 있는 것으로 가상되는 부분을 표시하는 데 사용한다."], answer: 4, explanation: "" },
  { id: 1087, subject: "제1편 가구와 목공에 설계", question: "다음 중 선의 굵기가 가장 굵은 것은?", image: "", options: ["도형의 중심을 나타내는 선", "지시 기호 등을 나타내기 위하여 사용한 선", "대상물의 보이는 부분의 윤곽을 표시한 선", "대상물의 보이지 않는 부분의 윤곽을 나타내는 선"], answer: 3, explanation: "" },
  { id: 1088, subject: "제1편 가구와 목공에 설계", question: "기계 제도에서 가는 실선으로 나타내는 것이 아닌 것은?", image: "", options: ["치수선", "회전 단면선", "외형선", "해칭선"], answer: 3, explanation: "" },
  { id: 1089, subject: "제1편 가구와 목공에 설계", question: "다음 선의 용도에 의한 명칭 중 선의 굵기가 다른 것은?", image: "", options: ["치수선", "지시선", "외형선", "치수 보조선"], answer: 3, explanation: "" },
  { id: 1090, subject: "제1편 가구와 목공에 설계", question: "도형이 이동한 중심 궤적을 표시할 때 사용하는 선은?", image: "", options: ["가는 실선", "굵은 실선", "가는 2점 쇄선", "가는 1점 쇄선"], answer: 4, explanation: "" },
  { id: 1091, subject: "제1편 가구와 목공에 설계", question: "반복 도형의 피치를 잡는 기준이 되는 피치선의 선 종류는?", image: "", options: ["가는 실선", "굵은 실선", "가는 1점 쇄선", "굵은 1점 쇄선"], answer: 3, explanation: "" },
  { id: 1092, subject: "제1편 가구와 목공에 설계", question: "도형의 중심을 표시하는 데 사용되는 선의 종류는?", image: "", options: ["굵은 실선", "가는 실선", "가는 1점 쇄선", "가는 2점 쇄선"], answer: 3, explanation: "" },
  { id: 1093, subject: "제1편 가구와 목공에 설계", question: "대상면의 일부에 특수한 가공을 하는 부분의 범위를 표시할 때 사용하는 선은?", image: "", options: ["굵은 1점 쇄선", "굵은 실선", "파선", "가는 2점 쇄선"], answer: 1, explanation: "" },
  { id: 1094, subject: "제1편 가구와 목공에 설계", question: "부품도에서 일부분만 부분적으로 열처리를 하도록 지시해야 한다면 열처리 범위를 나타내기 위해 사용하는 특수 지정선은?", image: "", options: ["굵은 1점 쇄선", "파선", "가는 1점 쇄선", "가는 실선"], answer: 1, explanation: "" },
  { id: 1095, subject: "제1편 가구와 목공에 설계", question: "그림에서 ①번 부위에 표시한 굵은 1점 쇄선이 의미하는 뜻은 무엇인가?", image: "", options: ["연삭 가공 부분", "열처리 부분", "다듬질 부분", "원형 가공 부분"], answer: 2, explanation: "" },
  { id: 1096, subject: "제1편 가구와 목공에 설계", question: "다음 그림에서 A 부분을 침탄 열처리를 하려고 할 때 표시하는 선으로 옳은 것은?", image: "", options: ["굵은 1점 쇄선", "가는 파선", "가는 실선", "가는 2점 쇄선"], answer: 1, explanation: "" },
  { id: 1097, subject: "제1편 가구와 목공에 설계", question: "물체의 가공 전이나 가공 후의 모양을 나타낼 때 사용되는 선의 종류는?", image: "", options: ["가는 2점 쇄선", "굵은 2점 쇄선", "가는 1점 쇄선", "굵은 1점 쇄선"], answer: 1, explanation: "" },
  { id: 1098, subject: "제1편 가구와 목공에 설계", question: "도면에서 사용되는 선 중에서 가는 2점 쇄선을 사용하는 것은?", image: "", options: ["치수를 기입하기 위한 선", "해칭선", "평면이란 것을 나타내는 선", "인접 부분을 참고로 표시하는 선"], answer: 4, explanation: "" },
  { id: 1099, subject: "제1편 가구와 목공에 설계", question: "선의 용도에 대한 설명으로 틀린 것은?", image: "", options: ["외형선 : 대상물의 보이는 부분의 겉모양을 표시하는 데 사용", "숨은선 : 대상물의 보이지 않는 부분의 모양을 표시하는 데 사용", "파단선 : 단면도를 그리기 위해 절단 위치를 나타내는 데 사용", "해칭선 : 단면도의 절단된 부분을 표시하는 데 사용"], answer: 3, explanation: "" },
  { id: 1100, subject: "제1편 가구와 목공에 설계", question: "둥근(원형)면에서 어느 부분의 면이 평면인 것을 나타낼 필요가 있을 경우 대각선을 그려 사용하는데 이때 사용되는 선으로 옳은 것은?", image: "", options: ["굵은 실선", "가는 실선", "굵은 1점 쇄선", "가는 1점 쇄선"], answer: 2, explanation: "" },
  { id: 1101, subject: "제1편 가구와 목공에 설계", question: "평화면에 수직인 직선은 입화면에 어떻게 나타나는가?", image: "", options: ["축소되어 나타난다.", "점으로 나타난다.", "수직으로 나타난다.", "실제 길이로 나타난다."], answer: 4, explanation: "" },
  { id: 1102, subject: "제1편 가구와 목공에 설계", question: "등각 투상도에 대한 설명으로 틀린 것은?", image: "", options: ["등각 투상도는 정면도, 평면도, 측면도가 필요하다.", "정면, 평면, 측면을 하나의 투상도에서 동시에 볼 수 있다.", "직육면체에서 직각으로 만나는 3개의 모서리는 120°를 이룬다.", "한 축이 수직일 때 나머지 두 축은 수평선과 30°를 이룬다."], answer: 1, explanation: "" },
  { id: 1103, subject: "제1편 가구와 목공에 설계", question: "다음 중 물체를 입체적으로 나타낸 도면이 아닌 것은?", image: "", options: ["투시도", "등각도", "캐비닛도", "정투상도"], answer: 4, explanation: "" },
  { id: 1104, subject: "제1편 가구와 목공에 설계", question: "원을 등각 투상법으로 투상하면 어떻게 나타나는가?", image: "", options: ["진원", "타원", "마름모", "직사각형"], answer: 2, explanation: "" },
  { id: 1105, subject: "제1편 가구와 목공에 설계", question: "등각 투상도에 대한 설명으로 틀린 것은?", image: "", options: ["원근감을 느낄 수 있도록 하나의 시점과 물체의 각 점을 방사선으로 이어서 그린다.", "한 축이 수직일 때 나머지 두 축은 수평선과 30°를 이룬다.", "직육면체에서 직각으로 만나는 3개의 모서리는 120°를 이룬다.", "정면, 평면, 측면을 하나의 투상도에서 동시에 볼 수 있다."], answer: 1, explanation: "" },
  { id: 1106, subject: "제1편 가구와 목공에 설계", question: "정면, 평면, 측면을 하나의 투상면 위에서 동시에 볼 수 있도록 그린 투상법은? 단, 인접한 두 축 사이의 각은 120°이다.", image: "", options: ["보조 투상도", "단면도", "등각 투상도", "전개도"], answer: 3, explanation: "" },
  { id: 1107, subject: "제1편 가구와 목공에 설계", question: "다음 설명과 관련된 투상법은? 하나의 그림으로 대상물의 한 면(정면)만을 중점적으로 엄밀하고 정확하게 표시할 수 있다. 물체를 투상면에 대하여 한쪽으로 경사지게 투상하여 입체적으로 나타낸 것이다.", image: "", options: ["사투상법", "등각 투상법", "투시 투상법", "부등각 투상법"], answer: 1, explanation: "" },
  { id: 1108, subject: "제1편 가구와 목공에 설계", question: "다음 그림과 같은 투상도는?", image: "", options: ["투상도", "사투상도", "등각 투상도", "부등각 투상도"], answer: 3, explanation: "" },
  { id: 1109, subject: "제1편 가구와 목공에 설계", question: "3개의 축선이 서로 만나서 이루는 세 각 중에서 두 각은 같고 나머지 한 각은 다르게 그린 투상도는?", image: "", options: ["등각 투상도", "부등각 투상도", "사투상도", "정투상도"], answer: 2, explanation: "" },
  { id: 1110, subject: "제1편 가구와 목공에 설계", question: "정육면체의 등각 투상도에서 3개의 축선 상호 간의 각도는 몇 도인가?", image: "", options: ["120°", "90°", "60°", "45°"], answer: 1, explanation: "" },
  { id: 1111, subject: "제1편 가구와 목공에 설계", question: "다음 그림과 같은 투상도는?", image: "", options: ["사투상도", "1점 투시도", "등각 투상도", "부등각 투상도"], answer: 1, explanation: "" },
  { id: 1112, subject: "제1편 가구와 목공에 설계", question: "다음 중 사투상도에 대한 설명으로 알맞지 않은 것은?", image: "", options: ["정면 모서리 길이와 경사축의 길이의 비가 1:1인 사투상도는 중세 때 축성 제도에 이용되었다.", "정면 모서리 길이와 경사축의 길이의 비가 1:1/2인 사투상도는 주로 가구 제작에 이용된다.", "사투상도에서 경사축의 경사각은 보통 수평선에 대하여 30°, 45°, 60°이다.", "길이가 긴 물체의 사투상도는 짧은 축을 수평으로 놓고 그리는 것이 좋다."], answer: 4, explanation: "" },
  { id: 1113, subject: "제1편 가구와 목공에 설계", question: "정투상도의 정면도를 이용하여 직접 작도할 수 있는 투상법은?", image: "", options: ["사투상도", "투시도", "등각 투상도", "부등각 투상도"], answer: 1, explanation: "" },
  { id: 1114, subject: "제1편 가구와 목공에 설계", question: "입체의 직립축과 수평축이 직각을 이루도록 한 면을 화면에 평행하게 놓고, 측면의 변을 기울어지게 그리는 투상도는?", image: "", options: ["투시도", "사투상도", "등축 투상도", "2축 투상도"], answer: 2, explanation: "" },
  { id: 1115, subject: "제1편 가구와 목공에 설계", question: "멀고 가까운 거리감을 느낄 수 있도록 하나의 시점과 물체의 각 점을 방사선으로 이어서 그리는 도법은?", image: "", options: ["등각 투상도", "부등각 투상도", "사투상도", "투시 투상도"], answer: 4, explanation: "" },
  { id: 1116, subject: "제1편 가구와 목공에 설계", question: "투시도의 작성법 중 구도를 결정할 때 시선의 각도는 몇 도 이내로 하는 것이 가장 자연스러운가?", image: "", options: ["15°", "30°", "45°", "60°"], answer: 4, explanation: "" },
  { id: 1117, subject: "제1편 가구와 목공에 설계", question: "다음 중 투시도를 그릴 때 불필요한 도면은 어느 것인가?", image: "", options: ["상세도", "정면도", "측면도", "평면도"], answer: 1, explanation: "" },
  { id: 1118, subject: "제1편 가구와 목공에 설계", question: "다음 중 투시법이 투상법과 다른 점이 아닌 것은?", image: "", options: ["투상도는 복잡하다.", "투시도는 원근감이 있다.", "투시도는 실제 치수가 정확히 나타나지 않는다.", "투상도는 등각일 경우 치수대로 그릴 수 있다."], answer: 1, explanation: "" },
  { id: 1119, subject: "제1편 가구와 목공에 설계", question: "다음 중 입체도법에 속하지 않는 것은?", image: "", options: ["평면도법", "투시 투상법", "등각 투상법", "정투상법"], answer: 1, explanation: "" },
  { id: 1120, subject: "제1편 가구와 목공에 설계", question: "다음 (　) 안에 알맞은 투상법은? 물체를 네모난 유리 상자 속에 넣고 밖에서 들여다보면 물체를 유리면에 투상하여 보는 것과 같다. 이때 투상선이 투상면에 대해 수직으로 투상하는 것을 (　)이라 한다.", image: "", options: ["투시법", "등각 투상법", "사투상법", "정투상법"], answer: 4, explanation: "" },
  { id: 1121, subject: "제1편 가구와 목공에 설계", question: "다음 중 원근감을 갖도록 나타낸 그림은?", image: "", options: ["투시도", "등각 투상도", "부등각 투상도", "정투상도"], answer: 1, explanation: "" },
  { id: 1122, subject: "제1편 가구와 목공에 설계", question: "투시도에서 물체를 보는 사람이 서 있는 위치를 칭하는 용어는?", image: "", options: ["SP", "VP", "PP", "HL"], answer: 1, explanation: "" },
  { id: 1123, subject: "제1편 가구와 목공에 설계", question: "투시법에서 사용되는 용어 중에서 화면(picture plane)이란?", image: "", options: ["사람이 서 있는 면", "물체와 시점 사이에 지면과 수직인 평면", "눈높이에 수평인 면", "사람이 서 있는 곳"], answer: 2, explanation: "" },
  { id: 1124, subject: "제1편 가구와 목공에 설계", question: "투시도의 용어와 그 의미가 바르게 짝지어지지 않은 것은?", image: "", options: ["PP : 화면", "HL : 수평선", "VL : 시선", "CV : 기선"], answer: 4, explanation: "" },
  { id: 1125, subject: "제1편 가구와 목공에 설계", question: "투시도와 관련된 용어 설명 중 틀린 것은?", image: "", options: ["SP : 입점 또는 정점", "PP : 물체와 시점 사이에 지면과 수직인 평면", "GL : 턱선의 높이와 수직선상의 정점", "VP : 물체의 각 점이 수평선상에 모이는 점"], answer: 3, explanation: "" },
  { id: 1126, subject: "제1편 가구와 목공에 설계", question: "평행 투시도에서 소실점의 수는?", image: "", options: ["1개", "2개", "3개", "없음"], answer: 1, explanation: "" },
  { id: 1127, subject: "제1편 가구와 목공에 설계", question: "기념물, 실내 투시도에 가장 많이 이용되는 투시도는?", image: "", options: ["1점 투시도", "2점 투시도", "3점 투시도", "유각 투시도"], answer: 1, explanation: "" },
  { id: 1128, subject: "제1편 가구와 목공에 설계", question: "유각 투시도는 소실점이 몇 개인가?", image: "", options: ["1개", "2개", "3개", "4개"], answer: 2, explanation: "" },
  { id: 1129, subject: "제1편 가구와 목공에 설계", question: "유각 투시도의 족선법에서 족선이란?", image: "", options: ["눈의 높이와 같은 화면상의 수평선", "화면과 지평면이 만나는 선", "입점에서 물체와 시점 간의 연결선", "지평면에서 물체와 입점 간의 연결선"], answer: 4, explanation: "" },
  { id: 1130, subject: "제1편 가구와 목공에 설계", question: "2점 투시도에서 소실점이 아주 낮은 경우 나타날 수 있는 현상은?", image: "", options: ["조감도에 가깝게 보인다.", "건물이 길게 보인다.", "건물이 작게 보인다.", "건물이 웅장해 보인다."], answer: 4, explanation: "" },
  { id: 1131, subject: "제1편 가구와 목공에 설계", question: "시점이 가장 높은 투시도는?", image: "", options: ["평행 투시도", "조감 투시도", "유각 투시도", "입체 투시도"], answer: 2, explanation: "" },
  { id: 1132, subject: "제1편 가구와 목공에 설계", question: "다음 물체의 정면도를 바르게 나타낸 것은? 단, 화살표 방향은 정면", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 4, explanation: "" },
  { id: 1133, subject: "제1편 가구와 목공에 설계", question: "정투상법 중 제3각법의 표현은 기준이 눈으로부터 어떤 순서로 위치하는가?", image: "", options: ["화면 - 눈 - 물체", "눈 - 물체 - 화면", "눈 - 화면 - 물체", "물체 - 눈 - 화면"], answer: 3, explanation: "" },
  { id: 1134, subject: "제1편 가구와 목공에 설계", question: "정투상법에서 물체를 위에서 수직으로 내려다본 상태의 그림을 무엇이라 하는가?", image: "", options: ["정면도", "평면도", "배면도", "측면도"], answer: 2, explanation: "" },
  { id: 1135, subject: "제1편 가구와 목공에 설계", question: "다음은 제3각법으로 정투상한 도면이다. 정투상도의 실제 입체로 알맞은 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 3, explanation: "" },
  { id: 1136, subject: "제1편 가구와 목공에 설계", question: "다음 그림과 같은 원리의 투상법은?", image: "", options: ["축측 투상", "사투상", "정투상", "단면 투상"], answer: 3, explanation: "" },
  { id: 1137, subject: "제1편 가구와 목공에 설계", question: "시점이 물체로부터 무한대의 거리에 있는 것으로 생각하고 투상하는 투상법은?", image: "", options: ["투시법", "등각 투상법", "사투상법", "정투상법"], answer: 4, explanation: "" },
  { id: 1138, subject: "제1편 가구와 목공에 설계", question: "다음 입체의 제3각법에 따른 우측면도를 바르게 나타낸 것은? 단, 화살표 방향이 정면이다.", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 4, explanation: "" },
  { id: 1139, subject: "제1편 가구와 목공에 설계", question: "직선의 투상에 관한 설명 중 틀린 것은?", image: "", options: ["직선이 평화면에 수직일 때 평화면 위의 투상도는 직선이 된다.", "직선이 입화면에 수직일 때 입화면 위의 투상도는 점이 된다.", "직선이 한 화면에 평행이고 다른 화면에 기울어지면 다른 투상도는 기선에 평행하고 길이가 짧아 보인다.", "직선이 두 화면과 모두 평행이 아니라면 투상도는 실제 길이 또는 각을 나타내지 않는다."], answer: 1, explanation: "" },
  { id: 1140, subject: "제1편 가구와 목공에 설계", question: "정투상도로 나타낼 수 없는 도면은?", image: "", options: ["정면도", "평면도", "배면도", "단면도"], answer: 4, explanation: "" },
  { id: 1141, subject: "제1편 가구와 목공에 설계", question: "정투상법에 관한 설명 중 틀린 것은?", image: "", options: ["한국산업표준에서는 제3각법으로 도면을 작성하는 것을 원칙으로 한다.", "한 도면에서 제1각법과 제3각법을 혼용하여 사용해도 좋다.", "제3각법은 눈 → 투상면 → 물체의 순서로 놓고 투상한다.", "제1각법에서 평면도는 정면도 아래에, 우측면도는 정면도 왼쪽에 배치한다."], answer: 2, explanation: "" },
  { id: 1142, subject: "제1편 가구와 목공에 설계", question: "보기와 같은 도형의 평면도를 나타낸 것으로 옳은 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 1, explanation: "" },
  { id: 1143, subject: "제1편 가구와 목공에 설계", question: "다음 그림에서 화살표 방향이 정면도일 때 평면도를 올바르게 표시한 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 2, explanation: "" },
  { id: 1144, subject: "제1편 가구와 목공에 설계", question: "다음 그림은 제3각법에 의한 투상도이다. 실제 물체의 모양으로 옳은 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 4, explanation: "" },
  { id: 1145, subject: "제1편 가구와 목공에 설계", question: "다음은 제3각법으로 정투상한 도면이다. 등각 투상도로 적합한 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 4, explanation: "" },
  { id: 1146, subject: "제1편 가구와 목공에 설계", question: "다음의 등각 투상도에서 화살표 방향을 정면도로 하여 제3각법으로 투상하였을 때 옳은 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 1, explanation: "" },
  { id: 1147, subject: "제1편 가구와 목공에 설계", question: "다음은 어떤 물체를 제3각법으로 투상하여 정면도와 우측면도를 나타낸 것이다. 평면도로 옳은 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 4, explanation: "" },
  { id: 1148, subject: "제1편 가구와 목공에 설계", question: "다음 도면은 제3각법에 의한 정면도와 평면도이다. 우측면도를 완성한 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 1, explanation: "" },
  { id: 1149, subject: "제1편 가구와 목공에 설계", question: "다음의 정면도에 해당되는 것을 고르면?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 2, explanation: "" },
  { id: 1150, subject: "제1편 가구와 목공에 설계", question: "어떤 물체를 제3각법으로 투상하여 나타낸 것이다. 정면도로 옳은 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 1, explanation: "" },
  { id: 1151, subject: "제1편 가구와 목공에 설계", question: "다음은 제3각법으로 정면도와 우측면도를 나타낸 것이다. ㉮에 들어갈 평면도로 알맞은 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 4, explanation: "" },
  { id: 1152, subject: "제1편 가구와 목공에 설계", question: "다음 그림과 같은 투상도의 명칭은?", image: "", options: ["부분 투상도", "보조 투상도", "국부 투상도", "회전 투상도"], answer: 2, explanation: "" },
  { id: 1153, subject: "제1편 가구와 목공에 설계", question: "투상도 표시에 대한 설명으로 틀린 것은?", image: "", options: ["주투상도는 대상물의 모양, 기능을 가장 명확하게 나타낼 수 있는 면을 선정하여 그린다.", "서로 관련된 그림을 배치할 때는 되도록 숨은선을 쓰지 않도록 한다.", "보조 투상도는 대상물의 구멍, 홈 등 일부 모양을 확대하여 도시한 것이다.", "주투상도를 보충하는 다른 투상도는 되도록 적게 한다."], answer: 3, explanation: "" },
  { id: 1154, subject: "제1편 가구와 목공에 설계", question: "보스에서 어느 각도만큼 암이 나와 있는 물체 등을 정투상도에 의해 나타내면 제도하기 어렵다. 이때 그 부분을 투상면에 평행한 위치까지 회전시켜 실제 길이가 나타날 수 있도록 그린 투상도는?", image: "", options: ["회전 투상도", "국부 투상도", "보조 투상도", "부분 투상도"], answer: 1, explanation: "" },
  { id: 1155, subject: "제1편 가구와 목공에 설계", question: "부품의 일부를 도시하는 것으로 충분한 경우 그 필요 부분만 도시하는 투상도는?", image: "", options: ["회전 투상도", "부분 투상도", "국부 투상도", "부분 확대도"], answer: 2, explanation: "" },
  { id: 1156, subject: "제1편 가구와 목공에 설계", question: "국부 투상도의 설명에 해당하는 것은?", image: "", options: ["대상물의 구멍, 홈 등과 같이 한 부분의 모양을 도시하는 것으로 충분한 경우의 투상도", "그림의 특정 부분만을 확대하여 그린 그림", "복잡한 물체를 절단하여 투상한 것", "물체의 경사면에 맞서는 위치에 그린 투상도"], answer: 1, explanation: "" },
  { id: 1157, subject: "제1편 가구와 목공에 설계", question: "부분 확대도의 도시 방법으로 틀린 것은?", image: "", options: ["특정한 부분의 도형이 작아서 그 부분을 확대하여 나타내는 표현 방법이다.", "확대할 부분을 굵은 실선으로 에워싸고 알파벳 대문자로 표시한다.", "확대도에는 치수 기입과 표면 거칠기를 표시할 수 있다.", "확대한 투상도 위에 확대를 표시하는 문자 기호와 척도를 기입한다."], answer: 2, explanation: "" },
  { id: 1158, subject: "제1편 가구와 목공에 설계", question: "대칭형 물체를 기본 중심에서 1/2 절단하여 그림과 같이 단면한 것은?", image: "", options: ["한쪽 단면도", "온 단면도", "부분 단면도", "회전 단면도"], answer: 2, explanation: "" },
  { id: 1159, subject: "제1편 가구와 목공에 설계", question: "한쪽 단면도는 대칭 모양의 물체를 중심선을 기준으로 얼마나 절단하여 나타내는가?", image: "", options: ["전체", "1/2", "1/4", "1/3"], answer: 3, explanation: "" },
  { id: 1160, subject: "제1편 가구와 목공에 설계", question: "다음 그림은 어떤 단면도에 해당하는가?", image: "", options: ["온 단면도", "한쪽 단면도", "회전 단면도", "부분 단면도"], answer: 4, explanation: "" },
  { id: 1161, subject: "제1편 가구와 목공에 설계", question: "단면도의 해칭 방법 중 틀린 것은?", image: "", options: ["조립도에서 인접하는 부품의 해칭은 선의 방향 또는 각도를 바꾸어 구별한다.", "절단 면적이 넓을 경우에는 외형선을 따라 적절히 해칭을 한다.", "해칭면에 문자, 기호 등을 기입할 경우 해칭을 중단해서는 안 된다.", "KS 규격에 제시된 재료의 단면 표시 기호를 사용할 수 있다."], answer: 3, explanation: "" },
  { id: 1162, subject: "제1편 가구와 목공에 설계", question: "도형의 생략에 관한 설명 중 틀린 것은?", image: "", options: ["대칭의 경우에는 대칭 중심선의 한쪽 도형만 그리고, 대칭 중심선의 양 끝부분에 짧은 2개의 나란한 가는 실선을 그린다.", "도면을 이해할 수 있더라도 숨은선은 생략해서는 안 된다.", "같은 종류, 같은 모양의 것이 다수 줄지어 있는 경우에는 지시선을 사용하여 기술할 수 있다.", "물체가 긴 경우 도면의 여백을 활용하기 위해 파단선이나 지그재그선을 사용하여 투상도를 단축할 수 있다."], answer: 2, explanation: "" },
  { id: 1163, subject: "제1편 가구와 목공에 설계", question: "기계요소 중 원칙적으로 길이 방향으로 절단하여 단면하지 않는 것으로 틀린 것은?", image: "", options: ["축, 키", "리벳, 핀", "볼트, 작은 나사", "베어링, 너트"], answer: 4, explanation: "" },
  { id: 1164, subject: "제1편 가구와 목공에 설계", question: "단면도를 나타낼 때 긴 쪽 방향으로 절단하여 도시할 수 있는 것은?", image: "", options: ["볼트, 너트, 와셔", "축, 핀, 리브", "리벳, 강구, 키", "기어의 보스"], answer: 4, explanation: "" },
  { id: 1165, subject: "제1편 가구와 목공에 설계", question: "치수 기입에서 (20)으로 표기된 것은 무엇을 뜻하는가?", image: "", options: ["기준 치수", "완성 치수", "참고 치수", "비례척이 아닌 치수"], answer: 3, explanation: "" },
  { id: 1166, subject: "제1편 가구와 목공에 설계", question: "다음 중 치수 기입의 원칙에 대한 설명으로 틀린 것은?", image: "", options: ["관련된 치수는 되도록 한 곳에 모아서 기입한다.", "치수는 중복 기입을 할 수 있으며, 각 투상도에 고르게 치수를 기입한다.", "치수는 되도록 주투상도에 집중한다.", "치수는 되도록 공정마다 배열을 분리하여 기입한다."], answer: 2, explanation: "" },
  { id: 1167, subject: "제1편 가구와 목공에 설계", question: "다음 중 치수 기입 방법에 대한 설명으로 틀린 것은?", image: "", options: ["치수의 자릿수가 많을 경우에는 세 자리 숫자마다 쉼표를 붙인다.", "길이 치수는 원칙적으로는 밀리미터(mm)의 단위로 기입하고, 단위 기호는 붙이지 않는다.", "각도 치수를 라디안의 단위로 기입하는 경우에는 단위 기호 rad를 기입한다.", "각도 치수는 일반적으로 도의 단위를 기입하고, 필요한 경우에는 분과 초를 같이 사용할 수 있다."], answer: 1, explanation: "" },
  { id: 1168, subject: "제1편 가구와 목공에 설계", question: "치수 기입의 요소가 아닌 것은?", image: "", options: ["치수선", "치수 보조선", "치수 숫자", "해칭선"], answer: 4, explanation: "" },
  { id: 1169, subject: "제1편 가구와 목공에 설계", question: "치수선과 치수 보조선에 대한 설명으로 틀린 것은?", image: "", options: ["치수선과 치수 보조선은 가는 실선을 사용한다.", "치수 보조선은 치수를 기입하는 형상에 대해 평행하게 그린다.", "외형선, 중심선, 기준선 및 이들의 연장선을 치수선으로 사용하지 않는다.", "치수 보조선과 치수선의 교차는 피해야 하나 불가피한 경우에는 끊김 없이 그린다."], answer: 2, explanation: "" },
  { id: 1170, subject: "제1편 가구와 목공에 설계", question: "치수선 끝에 붙는 화살표의 길이와 너비의 비율은 어떻게 되는가?", image: "", options: ["2 : 1", "3 : 1", "4 : 1", "5 : 1"], answer: 2, explanation: "" },
  { id: 1171, subject: "제1편 가구와 목공에 설계", question: "그림과 같이 여러 각도로 기울어진 면의 치수를 기입할 때 잘못 기입한 치수 방향은?", image: "", options: ["ㄱ", "ㄴ", "ㄷ", "ㄹ"], answer: 2, explanation: "" },
  { id: 1172, subject: "제1편 가구와 목공에 설계", question: "치수 기입에 관한 설명으로 틀린 것은?", image: "", options: ["수직 방향의 치수선에 대해서는 투상도의 오른쪽에서 읽을 수 있도록 기입한다.", "치수는 치수선 중앙의 위에 약간 띄어서 쓴다.", "비례척이 아닌 경우는 치수 위에 선을 긋는다.", "한 도면 내의 치수는 일정한 크기로 쓴다."], answer: 3, explanation: "" },
  { id: 1173, subject: "제1편 가구와 목공에 설계", question: "가구 제도 시 치수 기입에 대한 설명으로 옳지 않은 것은?", image: "", options: ["치수는 특별히 명시하지 않는 한 마무리 치수를 표시한다.", "치수는 치수선 중앙 상부에 기입하는 것이 원칙이다.", "협소한 간격이 연속될 때는 지시선을 그어 치수를 기입한다.", "치수의 단위는 cm를 사용함을 원칙으로 하고, 단위기호를 표시한다."], answer: 4, explanation: "" },
  { id: 1174, subject: "제1편 가구와 목공에 설계", question: "치수 기입법에 대한 설명으로 틀린 것은?", image: "", options: ["치수는 되도록 주투상도에 집중해서 지시한다.", "치수선에 평행하게 기입하며 치수선 위 중앙 부분에 기입한다.", "치수는 계산해서 구할 수 있도록 간단히 기입한다.", "치수의 단위는 mm를 기본으로 한다."], answer: 3, explanation: "" },
  { id: 1175, subject: "제1편 가구와 목공에 설계", question: "치수선 및 치수 보조선에 대한 설명으로 옳지 않은 것은?", image: "", options: ["도면에 방해가 되지 않는 적당한 위치에 긋는다.", "치수 보조선은 가는 실선으로 치수선에 직각으로 긋고, 치수선을 1520mm 넘게 연장한다.", "치수 보조선은 도면에서 23mm 정도 떨어져 긋기 시작한다.", "화살표 크기는 선의 굵기와 조화를 이루어야 한다."], answer: 2, explanation: "" },
  { id: 1176, subject: "제1편 가구와 목공에 설계", question: "도면에 사용되는 기호의 예로 옳은 것은?", image: "", options: ["두께 : t", "45° 모따기 : B", "반지름 : p", "지름 : R"], answer: 1, explanation: "" },
  { id: 1177, subject: "제1편 가구와 목공에 설계", question: "다음 투상도에 표시된 “SR”이 의미하는 것은?", image: "", options: ["호의 반지름", "호의 지름", "구의 반지름", "구의 지름"], answer: 3, explanation: "" },
  { id: 1178, subject: "제1편 가구와 목공에 설계", question: "45° 모따기(chamfering)의 기호로 사용되는 것은?", image: "", options: ["H", "F", "M", "C"], answer: 4, explanation: "" },
  { id: 1179, subject: "제1편 가구와 목공에 설계", question: "다음 중 치수 보조 기호의 사용 방법이 옳은 것은?", image: "", options: ["φ : 구의 지름 치수 앞에 붙인다.", "R : 원통의 지름 치수 앞에 붙인다.", "□ : 정육면체의 변의 치수 수치 앞에 붙인다.", "SR : 원형의 지름 치수 앞에 붙인다."], answer: 3, explanation: "" },
  { id: 1180, subject: "제1편 가구와 목공에 설계", question: "호의 반지름을 기입하는 방법으로 틀린 것은 어느 것인가?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 4, explanation: "" },
  { id: 1181, subject: "제1편 가구와 목공에 설계", question: "원호의 길이를 나타내는 치수선과 치수 보조선의 도시 방법으로 옳은 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 1, explanation: "" },
  { id: 1182, subject: "제1편 가구와 목공에 설계", question: "다음 중 각도 치수가 잘못 기입된 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 1, explanation: "" },
  { id: 1183, subject: "제1편 가구와 목공에 설계", question: "다음 그림과 같이 테이퍼 1/200로 표시되어 있는 경우 X 부분의 치수는?", image: "", options: ["89", "92", "96", "98"], answer: 4, explanation: "" },
  { id: 1184, subject: "제1편 가구와 목공에 설계", question: "다음 그림에서 φ20 구멍의 개수와 A 부분의 길이는?", image: "", options: ["13, 1170mm", "20, 1170mm", "13, 1080mm", "20, 1080mm"], answer: 3, explanation: "" },
  { id: 1185, subject: "제1편 가구와 목공에 설계", question: "다음 도면에서 전체 길이 A는?", image: "", options: ["700mm", "800mm", "900mm", "1000mm"], answer: 4, explanation: "" },
  { id: 1186, subject: "제1편 가구와 목공에 설계", question: "다음 테이퍼 표기법 중 표기 방법이 틀린 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 2, explanation: "" },
  { id: 1187, subject: "제1편 가구와 목공에 설계", question: "다음 그림에서 모따기가 C2일 때 모따기의 각도는?", image: "", options: ["15°", "30°", "45°", "60°"], answer: 3, explanation: "" },
  { id: 1188, subject: "제1편 가구와 목공에 설계", question: "다음은 축의 도시에 대한 설명이다. 옳은 것은?", image: "", options: ["긴 축은 중간 부분을 파단하여 짧게 그리며, 그림의 80은 짧게 줄인 치수이다.", "축의 끝에는 모따기를 하고 모따기 치수는 그림과 같이 기입할 수 있다.", "그림은 축에 단을 주는 치수 기입으로, 홈의 너비가 12mm, 홈의 지름이 12mm이다.", "그림은 빗줄 널링에 대한 도시이며, 축선에 대하여 45° 엇갈리게 그린다."], answer: 2, explanation: "" },
  { id: 1189, subject: "제1편 가구와 목공에 설계", question: "다음 치수 기입법 중 틀린 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 4, explanation: "" },
  { id: 1190, subject: "제1편 가구와 목공에 설계", question: "치수 기입 시 유의사항으로 틀린 것은?", image: "", options: ["치수 숫자는 선에 겹쳐서 기입하지 않는다.", "인접한 치수는 치수선이 일직선상에 있도록 한다.", "치수 숫자와 선이 겹칠 때는 선이 겹치는 부분을 중단하고 치수를 기입한다.", "치수선이 길어서 치수를 알아보기 어렵더라도 치수 숫자를 한쪽 끝에 기입하지 않는다."], answer: 4, explanation: "" },
  { id: 1191, subject: "제1편 가구와 목공에 설계", question: "경사진 두 면의 만나는 부분이 둥글게 되었을 때의 치수 기입 방법으로 가장 적당한 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 3, explanation: "" },
  { id: 1192, subject: "제1편 가구와 목공에 설계", question: "좁은 곳에서의 치수 기입 방법으로 잘못된 것은?", image: "", options: ["부분 확대도를 그려서 기입한다.", "지시선을 끌어내어 치수를 기입한다.", "치수선을 연장하여 바깥쪽에 기입한다.", "치수 보조선의 간격이 좁을 때는 화살표를 겹쳐서 그린다."], answer: 4, explanation: "" },
  { id: 1193, subject: "제1편 가구와 목공에 설계", question: "창호 기호 중 철재창을 표시한 것은?", image: "", options: ["1/WW", "1/WD", "1/SW", "1/SD"], answer: 3, explanation: "" },
  { id: 1194, subject: "제1편 가구와 목공에 설계", question: "다음 중 방위 표시 기호가 아닌 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 2, explanation: "" },
  { id: 1195, subject: "제1편 가구와 목공에 설계", question: "입면 방향 표시 기호가 아닌 것은?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 3, explanation: "" },
  { id: 1196, subject: "제1편 가구와 목공에 설계", question: "도면 표시 기호가 잘못 연결된 것은?", image: "", options: ["H - 높이", "THK - 두께", "φ - 반지름", "Wt - 두께"], answer: 3, explanation: "" },
  { id: 1197, subject: "제1편 가구와 목공에 설계", question: "다음 창호 표시 기호가 나타내는 것은?", image: "", options: ["회전문", "쌍여닫이문", "자재문", "빈지문"], answer: 3, explanation: "" },
  { id: 1198, subject: "제1편 가구와 목공에 설계", question: "치장 합판 표시 기호는 어느 것인가?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 2, explanation: "" },
  { id: 1199, subject: "제1편 가구와 목공에 설계", question: "다음 중 하드보드 표시 기호는?", image: "", options: ["1번 그림", "2번 그림", "3번 그림", "4번 그림"], answer: 3, explanation: "" },
  { id: 1200, subject: "제1편 가구와 목공에 설계", question: "다음의 원가 구성에 해당하는 것은? 재료비 + 노무비 + 일반 관리비", image: "", options: ["판매가", "간접원가", "제조원가", "총원가"], answer: 3, explanation: "" },
  { id: 1201, subject: "제1편 가구와 목공에 설계", question: "온라인 업체의 공급 제품가를 결정하는 과정에 대한 설명으로 옳지 않은 것은?", image: "", options: ["온라인 업체의 현황을 조사한다.", "소비자가 대비 할인율을 조사한다.", "경쟁업체의 유사 품목에 대한 판매량을 분석한다.", "경쟁업체와 자사 간 온라인 가격 구조를 확인한다."], answer: 2, explanation: "" },
  { id: 1202, subject: "제1편 가구와 목공에 설계", question: "다음 중 가구 제품 시방서 포함 사항이 아닌 것은?", image: "", options: ["재료 관련 사항", "조립 관련 사항", "도장 관련 사항", "견적서 제출 장소"], answer: 4, explanation: "" },
  { id: 1203, subject: "제1편 가구와 목공에 설계", question: "다음 중 내용에 따른 시방서의 종류와 관련 없는 것은?", image: "", options: ["표준 시방서", "일반 시방서", "서술 시방서", "특기 시방서"], answer: 3, explanation: "" },
  { id: 1204, subject: "제1편 가구와 목공에 설계", question: "작성 방법에 따른 시방서 종류에 해당하지 않는 것은?", image: "", options: ["서술 시방서", "성능 시방서", "참조 시방서", "개요 시방서"], answer: 4, explanation: "" },
  { id: 1205, subject: "제1편 가구와 목공에 설계", question: "사용 목적에 따라 시방서를 분류했을 때 해당사항이 없는 것은?", image: "", options: ["참조 시방서", "개요 시방서", "가이드 시방서", "자재 생산업자 시방서"], answer: 1, explanation: "" },
  { id: 1206, subject: "제1편 가구와 목공에 설계", question: "제품 시방서 작성 시 고려할 사항이 아닌 것은?", image: "", options: ["재료의 구체적인 내용", "가구 조립의 상세 내용", "사용 부자재의 시중 가격에 관한 사항", "파손 등의 책임 규명에 관한 사항"], answer: 3, explanation: "" },
  { id: 1207, subject: "제1편 가구와 목공에 설계", question: "기본 설계에서부터 상세 설계 및 도면 작성에 이르는 설계의 전 과정을 컴퓨터를 이용하여 작업하는 것을 이르는 용어는?", image: "", options: ["CAM", "CAD", "CAE", "CAT"], answer: 2, explanation: "" },
  { id: 1208, subject: "제1편 가구와 목공에 설계", question: "CAD 시스템으로 이용할 수 있는 작업과 거리가 먼 것은?", image: "", options: ["기하학적 모델링", "강도 및 열 전달 계산 등 공학적 분석", "설계의 정확도를 검사하는 평가", "NC 코드의 작성"], answer: 4, explanation: "" },
  { id: 1209, subject: "제1편 가구와 목공에 설계", question: "CAD 시스템의 효과라고 볼 수 없는 것은?", image: "", options: ["고도의 설계 기능", "제품의 표준화", "제품 제도의 데이터베이스 구축화", "설계 생산량 증가"], answer: 1, explanation: "" },
  { id: 1210, subject: "제1편 가구와 목공에 설계", question: "다음 중 컴퓨터 중앙처리장치의 구성요소가 아닌 것은?", image: "", options: ["제어장치", "주기억장치", "연산장치", "입출력장치"], answer: 4, explanation: "" },
  { id: 1211, subject: "제1편 가구와 목공에 설계", question: "다음 중 CAD 시스템의 출력장치에 해당하는 것은?", image: "", options: ["마우스", "스캐너", "하드카피", "태블릿"], answer: 3, explanation: "" },
  { id: 1212, subject: "제1편 가구와 목공에 설계", question: "CAD 시스템에서 도면의 요소를 용지에 출력하는 장치는?", image: "", options: ["모니터", "플로터", "LCD", "디지타이저"], answer: 2, explanation: "" },
  { id: 1213, subject: "제1편 가구와 목공에 설계", question: "2D 도면에서 원을 작도하는 옵션이 아닌 것은?", image: "", options: ["2점", "3점", "접선-접선", "중심점-반지름"], answer: 3, explanation: "" },
  { id: 1214, subject: "제1편 가구와 목공에 설계", question: "2D 도면을 CAD에서 작성할 때 객체를 이동시키는 편집 명령어는?", image: "", options: ["M", "PL", "AR", "DI"], answer: 1, explanation: "" },
]);
