// questions/p1.js — 제1편 가구와 목공에 설계
// id 규칙: 10xx (1001, 1002, ...)
window.QUESTIONS = (window.QUESTIONS || []).concat([
  {id:1001,subject:"제1편 가구와 목공에 설계",question:"디바이더의 사용법 중 틀린 것은?",image:"",options:["치수를 도면에 옮길 때","작은 원을 그릴 때","선을 일정한 간격으로 분할할 때","도면의 길이를 다른 도면에 옮길 때"],answer:2,explanation:""},
  {id:1002,subject:"제1편 가구와 목공에 설계",question:"컴퍼스를 사용하여 원을 그리는 방향은?",image:"",options:["시계 방향","반시계 방향","앞 오른쪽에서 시계 반대 방향","방향에 무관"],answer:1,explanation:""},
  {id:1003,subject:"제1편 가구와 목공에 설계",question:"축척 눈금을 제도용지에 옮기거나 도면 위의 선을 등분할 때 사용하는 제도 용구는?",image:"",options:["빔 컴퍼스","디바이더","삼각자","먹줄펜"],answer:2,explanation:""},
  {id:1004,subject:"제1편 가구와 목공에 설계",question:"가장 큰 원을 그릴 수 있는 컴퍼스는?",image:"",options:["대형 컴퍼스","중형 컴퍼스","빔 컴퍼스","스프링 컴퍼스"],answer:3,explanation:""},
  {id:1005,subject:"제1편 가구와 목공에 설계",question:"먹줄펜의 종류에 속하지 않는 것은?",image:"",options:["보통 먹줄펜","점선 먹줄펜","양머리 곡선 먹줄펜","채석 먹줄펜"],answer:4,explanation:""},
  {id:1006,subject:"제1편 가구와 목공에 설계",question:"다음 중 디바이더를 사용하기에 적합한 경우는?",image:"",options:["직선을 그을 때","선을 등분할 때","줄여서 그릴 때","곡선을 그릴 때"],answer:2,explanation:""},
  {id:1007,subject:"제1편 가구와 목공에 설계",question:"그림에서 각 A는 몇 도인가?",image:"",options:["15°","30°","45°","60°"],answer:1,explanation:""},
  {id:1008,subject:"제1편 가구와 목공에 설계",question:"여러 가지 곡선을 자유롭게 그릴 때 사용하는 제도 용구로, 납과 고무로 만들어져 자유롭게 구부릴 수 있는 것은?",image:"",options:["운형자","축척자","형판","자유곡선자"],answer:4,explanation:""},
  {id:1009,subject:"제1편 가구와 목공에 설계",question:"삼각스케일에 대한 설명으로 틀린 것은?",image:"",options:["임의의 축척으로 도면을 그릴 때 사용한다.","1/100, 1/200, 1/300, 1/400, 1/500, 1/600의 6가지 축척 눈금이 있다.","1/10, 1/20, 1/30 등의 도면을 작도할 때도 사용한다.","길이를 재거나 길이를 줄여 그릴 때 사용한다."],answer:1,explanation:""},
  {id:1010,subject:"제1편 가구와 목공에 설계",question:"축척자(scale ruler)의 축척 눈금에 해당하지 않는 것은?",image:"",options:["1/300","1/500","1/600","1/700"],answer:4,explanation:""},
  {id:1011,subject:"제1편 가구와 목공에 설계",question:"삼각자의 크기는 어느 부분을 기준으로 하는가?",image:"",options:["45° 자의 빗변과 60° 자의 수선 길이","45° 자의 빗변과 60° 자의 빗변 길이","45° 자의 수선 길이와 60° 자의 빗변 길이","45° 자의 수선 길이와 60° 자의 수선 길이"],answer:1,explanation:""},
  {id:1012,subject:"제1편 가구와 목공에 설계",question:"T자와 삼각자의 사용법에 대하여 바르게 설명한 것은?",image:"",options:["수평선은 우측에서 좌측으로 선을 긋는다.","수직선은 위에서 아래로 긋는다.","경사선은 T자를 경사로 놓고 긋는다.","수평선과 수직선을 긋는 데 사용한다."],answer:4,explanation:""},
  {id:1013,subject:"제1편 가구와 목공에 설계",question:"다음 중 디바이더의 용도가 아닌 것은?",image:"",options:["제도용지에 호를 그린다.","직선을 일정한 치수로 나눈다.","도면 위의 길이를 재어 다른 곳에 옮긴다.","원둘레를 등분한다."],answer:1,explanation:""},
  {id:1014,subject:"제1편 가구와 목공에 설계",question:"다음과 같은 그림을 그리기 위한 제도 용구가 아닌 것은?",image:"",options:["T자","삼각자","운형자","디바이더"],answer:4,explanation:""},
  {id:1015,subject:"제1편 가구와 목공에 설계",question:"다음 연필 중 경도가 가장 낮은 것은?",image:"",options:["H","F","HB","B"],answer:4,explanation:""},
  {id:1016,subject:"제1편 가구와 목공에 설계",question:"제도판에 있어서 중판의 규격으로 알맞은 것은?",image:"",options:["600×450mm","900×600mm","1000×750mm","1200×900mm"],answer:2,explanation:""},
  {id:1017,subject:"제1편 가구와 목공에 설계",question:"합판으로 만든 제도판의 올거미 재료로 적합하지 않은 것은?",image:"",options:["춘양목","나왕","벚나무","낙엽송"],answer:4,explanation:""},
  {id:1018,subject:"제1편 가구와 목공에 설계",question:"제도판에 대한 설명으로 옳지 않은 것은?",image:"",options:["뒤틀림이 없어야 한다.","두께는 두꺼울수록 좋다.","표면이 평평해야 한다.","크기는 특대판, 대판, 중판, 소판으로 구분한다."],answer:2,explanation:""},
  {id:1019,subject:"제1편 가구와 목공에 설계",question:"다음 중 만능 제도기의 기능에 해당하지 않는 것은?",image:"",options:["삼각자 기능","T자 기능","운형자 기능","각도기 기능"],answer:3,explanation:""},
  {id:1020,subject:"제1편 가구와 목공에 설계",question:"직선 A, B에서 점 B에 수선을 긋는 방법으로 옳지 않은 것은?",image:"",options:["CB = CD","CD = DE","DF = EF","BG = FG"],answer:4,explanation:""},
  {id:1021,subject:"제1편 가구와 목공에 설계",question:"다음 그림과 같이 주어진 직선 AB를 수직 2등분할 때 옳지 않은 것은?",image:"",options:["AE = BE","AC = BC","AE = CE","CD ⊥ AB"],answer:3,explanation:""},
  {id:1022,subject:"제1편 가구와 목공에 설계",question:"선분 AB를 다음 그림과 같이 나타낸 것은 어떤 기하학적 원리를 의미하는가?",image:"",options:["평행","대칭","합동","균형"],answer:1,explanation:""},
  {id:1023,subject:"제1편 가구와 목공에 설계",question:"다음은 직각을 3등분한 그림이다. 길이에 관한 설명으로 틀린 것은?",image:"",options:["AD = DC","OA = AD","AD = BC","DC = BC"],answer:2,explanation:""},
  {id:1024,subject:"제1편 가구와 목공에 설계",question:"직사각형과 같은 넓이의 정사각형 그리기에서 옳은 것은?",image:"",options:["DF = FE","BC = CG","CE = CG","DF = FH"],answer:1,explanation:""},
  {id:1025,subject:"제1편 가구와 목공에 설계",question:"원과 같은 넓이의 정사각형을 작도할 때, 각각 어느 점을 중심으로 하여 AB를 반지름으로 호를 그리면 되는가?",image:"",options:["A, B","C, D","E, F","B, D"],answer:4,explanation:""},
  {id:1026,subject:"제1편 가구와 목공에 설계",question:"원의 반지름으로 원주를 끊고, 그 끊은 점과 점을 연결하여 만들어진 원에 접하는 다각형은?",image:"",options:["정사각형","정오각형","정육각형","정팔각형"],answer:3,explanation:""},
  {id:1027,subject:"제1편 가구와 목공에 설계",question:"원에 내접하는 정오각형을 그리는 방법이 아닌 것은?",image:"",options:["AO ⊥ KL","OM = ML","AM = MN","AM = AB"],answer:4,explanation:""},
  {id:1028,subject:"제1편 가구와 목공에 설계",question:"한 변이 주어진 정오각형 작도 그림에서 DE의 길이는?",image:"",options:["AD/2","AD/3","AB/2","CF/4"],answer:3,explanation:""},
  {id:1029,subject:"제1편 가구와 목공에 설계",question:"다음은 AB를 한 변으로 하는 정육각형을 그리는 작도이다. 순서상 가장 먼저 구해야 할 점은?",image:"",options:["C","O","D","E"],answer:2,explanation:""},
  {id:1030,subject:"제1편 가구와 목공에 설계",question:"장축과 단축이 주어진 타원을 그릴 때의 작도 조건이 아닌 것은?",image:"",options:["1/2 EF = G","FH = OF","AE = CO","OE = OF"],answer:2,explanation:""},
  {id:1031,subject:"제1편 가구와 목공에 설계",question:"다음 그림과 같은 표준 난형 작도에서 CE의 중심은?",image:"",options:["A","B","C","D"],answer:4,explanation:""},
  {id:1032,subject:"제1편 가구와 목공에 설계",question:"단면 상세도를 그릴 때 표시하지 않아도 되는 것은?",image:"",options:["각 실의 면적","1층 바닥의 높이","지붕 물매","창의 높이"],answer:1,explanation:""},
  {id:1033,subject:"제1편 가구와 목공에 설계",question:"평면도를 작도할 때 고려하지 않아도 되는 것은?",image:"",options:["개구부의 위치와 크기","실의 배치와 넓이","기둥이나 벽의 위치","처마 높이 및 지붕 재료"],answer:4,explanation:""},
  {id:1034,subject:"제1편 가구와 목공에 설계",question:"건물의 외관을 나타내는 입면도 중 정면도를 가장 잘 표현한 것은?",image:"",options:["개구부가 많이 있는 쪽","복잡한 입면이 있는 쪽","현관이 있는 쪽","도로에 면한 쪽"],answer:3,explanation:""},
  {id:1035,subject:"제1편 가구와 목공에 설계",question:"절단면의 실제 모양을 나타내는 도면은?",image:"",options:["절단선","보조 투상면","단면도","정투상도"],answer:3,explanation:""},
  {id:1036,subject:"제1편 가구와 목공에 설계",question:"건축 도면에서 각 실의 크기, 위치 등을 표시하는 도면은?",image:"",options:["평면도","입면도","단면도","투시도"],answer:1,explanation:""},
  {id:1037,subject:"제1편 가구와 목공에 설계",question:"건축 도면 중 바닥으로부터 1~1.5m 정도 윗부분을 수평으로 절단한 것을 상상하여 그린 것으로, 건축 도면의 기본이라 할 수 있는 것은?",image:"",options:["평면도","입면도","부분 단면도","투시도"],answer:1,explanation:""},
  {id:1038,subject:"제1편 가구와 목공에 설계",question:"입체의 각 면을 한 면 위에 펴서 그린 도면을 무엇이라 하는가?",image:"",options:["투시도","상관체","전개도","음영도"],answer:3,explanation:""},
  {id:1039,subject:"제1편 가구와 목공에 설계",question:"다음 그림과 같은 전개도의 입체는?",image:"",options:["정사면체","정사각뿔","정삼각뿔","삼각뿔"],answer:3,explanation:""},
  {id:1040,subject:"제1편 가구와 목공에 설계",question:"정상각형으로만 구성되어 있는 입체는?",image:"",options:["정사면체","정육면체","정십면체","정십이면체"],answer:1,explanation:""},
  {id:1041,subject:"제1편 가구와 목공에 설계",question:"도면에서 평면도, 배치도 등은 원칙적으로 어느 방향을 위로 하여 제도하는가?",image:"",options:["동","서","남","북"],answer:4,explanation:""},
  {id:1042,subject:"제1편 가구와 목공에 설계",question:"다음 그림은 어떤 입체의 전개도인가?",image:"",options:["정6각형","정12면체","정10면체","정6면체"],answer:2,explanation:""},
  {id:1043,subject:"제1편 가구와 목공에 설계",question:"다음 중 국제표준규격을 나타내는 것은?",image:"",options:["ISO","BS","KS","ASA"],answer:1,explanation:""},
  {id:1044,subject:"제1편 가구와 목공에 설계",question:"건물 내부의 입면을 정면에서 바라보고 그리는 내부 입면도를 나타내는 것은?",image:"",options:["투시도","단면도","전개도","음영도"],answer:3,explanation:""},
  {id:1045,subject:"제1편 가구와 목공에 설계",question:"도면 제작 시 도면에 반드시 마련해야 할 사항으로 짝지어진 것은?",image:"",options:["도면의 윤곽, 표제란, 중심 마크","도면의 윤곽, 표제란, 비교 눈금","도면의 구역, 재단 마크, 비교 눈금","도면의 구역, 재단 마크, 중심 마크"],answer:1,explanation:""},
  {id:1046,subject:"제1편 가구와 목공에 설계",question:"도면에서 도면의 관리상 필요한 사항과 도면 내에 있는 내용에 관한 사항을 모아서 기입한 것은?",image:"",options:["주서란","요목표","표제란","부품란"],answer:3,explanation:""},
  {id:1047,subject:"제1편 가구와 목공에 설계",question:"도면 관리에서 다른 도면과 구별하고, 도면 내용을 직접 보지 않고도 제품의 종류 및 형식 등 도면의 내용을 알 수 있게 하기 위해 기입하는 것은?",image:"",options:["도면 번호","도면 척도","도면 양식","부품 번호"],answer:1,explanation:""},
  {id:1048,subject:"제1편 가구와 목공에 설계",question:"도면에 반드시 마련해야 하는 양식에 관한 설명 중 틀린 것은?",image:"",options:["윤곽선은 도면의 크기에 따라 0.7mm 이상의 굵은 실선으로 그린다.","표제란은 도면의 오른쪽 아래 구석에 그린다.","도면을 마이크로필름으로 촬영하거나 복사할 때 편의를 위해서 중심 마크를 표시한다.","부품란에는 도면 번호, 도면 명칭, 척도, 투상법 등을 기입한다."],answer:4,explanation:""},
  {id:1049,subject:"제1편 가구와 목공에 설계",question:"도면에 마련하는 양식 중에서 마이크로필름 등으로 촬영하거나 복사 및 철할 때의 편의를 위해 마련하는 것은?",image:"",options:["윤곽선","표제란","중심 마크","구역 표시"],answer:3,explanation:""},
  {id:1050,subject:"제1편 가구와 목공에 설계",question:"기계 제도 도면에 사용되는 척도의 설명이 틀린 것은?",image:"",options:["도면에 그려지는 길이와 대상물의 실제 길이와의 비율로 나타낸다.","한 도면에서 공통적으로 사용되는 척도는 표제란에 기입된다.","같은 도면에서 다른 척도를 사용할 때는 필요에 따라 그림 근처에 기입한다.","배척은 대상물보다 크게 그리는 것으로 2:1, 3:1, 4:1, 10:1 등 제도자 임의로 비율을 만들어 사용한다."],answer:4,explanation:""},
  {id:1051,subject:"제1편 가구와 목공에 설계",question:"다음 그림과 같은 도면 양식에 관한 설명 중 틀린 것은?",image:"",options:["ⓐ는 0.7mm 이상의 굵은 실선으로 긋고 도면의 윤곽을 나타내는 선이다.","ⓑ는 0.7mm 이상의 굵은 실선으로 긋고 마이크로필름으로 촬영할 때 편의를 위해 사용한다.","ⓒ는 도면에서 상세, 추가, 수정 등의 위치를 알기 쉽도록 용지를 여러 구역으로 나누는 데 사용된다.","ⓓ는 표제란으로 척도, 투상법, 도면, 도명, 설계자, 기업명 등 도면에 관한 정보를 표시한다."],answer:3,explanation:""},
  {id:1052,subject:"제1편 가구와 목공에 설계",question:"다음 중 부품란에 기입해야 할 사항이 아닌 것은?",image:"",options:["품번","품명","재질","투상법"],answer:4,explanation:""},
  {id:1053,subject:"제1편 가구와 목공에 설계",question:"우선적으로 사용하는 배척의 종류가 아닌 것은?",image:"",options:["50 : 1","25 : 1","5 : 1","2 : 1"],answer:2,explanation:""},
  {id:1054,subject:"제1편 가구와 목공에 설계",question:"도면을 그릴 때 척도 결정의 기준이 되는 것은 어느 것인가?",image:"",options:["물체의 재질","물체의 무게","물체의 크기","물체의 체적"],answer:3,explanation:""},
  {id:1055,subject:"제1편 가구와 목공에 설계",question:"다음 중 현척의 의미는?",image:"",options:["실물보다 축소하여 그린 것","실물보다 확대하여 그린 것","실물과 관계없이 그린 것","실물과 같은 크기로 그린 것"],answer:4,explanation:""},
  {id:1056,subject:"제1편 가구와 목공에 설계",question:"다음 축척의 종류 중 우선적으로 사용되는 척도가 아닌 것은?",image:"",options:["1 : 2","1 : 3","1 : 5","1 : 10"],answer:2,explanation:""},
  {id:1057,subject:"제1편 가구와 목공에 설계",question:"다음 중 척도의 표시법 A : B의 설명으로 맞는 것은?",image:"",options:["A는 물체의 실제 크기이다.","B는 도면에서의 크기이다.","배척일 때 B를 1로 나타낸다.","현척일 때 A만을 1로 나타낸다."],answer:3,explanation:""},
  {id:1058,subject:"제1편 가구와 목공에 설계",question:"도면의 표제란에 척도가 1 : 2로 기입되어 있다면 이 도면에서 사용된 척도의 종류로 알맞은 것은?",image:"",options:["현척","배척","축척","실척"],answer:3,explanation:""},
  {id:1059,subject:"제1편 가구와 목공에 설계",question:"도면에서 100mm를 2 : 1 척도로 그릴 때 도면에 기입되는 치수는?",image:"",options:["10","200","50","100"],answer:4,explanation:""},
  {id:1060,subject:"제1편 가구와 목공에 설계",question:"제도용지 전지를 그림과 같이 등분했을 때 빗금친 부분의 크기는?",image:"",options:["A1","A2","A3","A4"],answer:2,explanation:""},
  {id:1061,subject:"제1편 가구와 목공에 설계",question:"도면에서 세로와 가로의 비는?",image:"",options:["1 : √2","1 : √3","1 : √5","1 : √8"],answer:1,explanation:""},
  {id:1062,subject:"제1편 가구와 목공에 설계",question:"A0 제도용지의 크기는? 단, 단위는 mm",image:"",options:["210×297","297×420","594×841","841×1189"],answer:4,explanation:""},
  {id:1063,subject:"제1편 가구와 목공에 설계",question:"도면을 접을 때 표준 크기로 옳은 것은?",image:"",options:["A0","A1","A2","A4"],answer:4,explanation:""},
  {id:1064,subject:"제1편 가구와 목공에 설계",question:"도면을 접을 때 겉으로 드러나게 정리해야 하는 부분은?",image:"",options:["조립도가 있는 부분","표제란이 있는 부분","재료표가 있는 부분","부품도가 있는 부분"],answer:2,explanation:""},
  {id:1065,subject:"제1편 가구와 목공에 설계",question:"도면에서 표제란이 위치하는 곳은 다음 중 어디인가?",image:"",options:["도면의 오른쪽 위","도면의 오른쪽 아래","도면의 왼쪽 아래","도면의 왼쪽 위"],answer:2,explanation:""},
  {id:1066,subject:"제1편 가구와 목공에 설계",question:"다음 중 도면의 표제란에 표기하지 않아도 되는 것은?",image:"",options:["재료 명칭","도면 번호","도면 이름","작성 연월일"],answer:1,explanation:""},
  {id:1067,subject:"제1편 가구와 목공에 설계",question:"제도를 할 때의 주의사항으로 옳지 않은 것은?",image:"",options:["축척에 맞추어 그린 것이 아닐 때는 NS를 기입한다.","도면은 제3각법으로 그리는 것을 원칙으로 한다.","복잡한 부분의 제도에서는 실척을 사용할 수 있다.","축척의 종류에는 3가지가 있다."],answer:4,explanation:""},
  {id:1068,subject:"제1편 가구와 목공에 설계",question:"다음 중 축척의 척도는 어느 것인가?",image:"",options:["1/2","1/1","2/1","4/1"],answer:1,explanation:""},
  {id:1069,subject:"제1편 가구와 목공에 설계",question:"500×100의 넓이를 가진 널빤지를 제작하기 위해 10 : 1의 비로 도면을 그렸다. 기입해야 할 치수는?",image:"",options:["5×1","50×10","500×100","5000×1000"],answer:3,explanation:""},
  {id:1070,subject:"제1편 가구와 목공에 설계",question:"일정한 척도로 그리지 않아서 그림이 치수에 비례하지 않을 때 표제란에는 어떻게 표시하는가?",image:"",options:["A : B","NS","0 : 0","1 : 0"],answer:2,explanation:""},
  {id:1071,subject:"제1편 가구와 목공에 설계",question:"실제 길이 32m를 축척 1/200으로 계산한 값은?",image:"",options:["8cm","12cm","16cm","64cm"],answer:3,explanation:""},
  {id:1149,subject:"제1편 가구와 목공에 설계",question:"다음의 정면도에 해당되는 것을 고르면?",image:"",options:["1번 그림","2번 그림","3번 그림","4번 그림"],answer:2,explanation:""},
  {id:1150,subject:"제1편 가구와 목공에 설계",question:"어떤 물체를 제3각법으로 투상하여 나타낸 것이다. 정면도로 옳은 것은?",image:"",options:["1번 그림","2번 그림","3번 그림","4번 그림"],answer:1,explanation:""},
  {id:1151,subject:"제1편 가구와 목공에 설계",question:"다음은 제3각법으로 정면도와 우측면도를 나타낸 것이다. ㉮에 들어갈 평면도로 알맞은 것은?",image:"",options:["1번 그림","2번 그림","3번 그림","4번 그림"],answer:4,explanation:""},
  {id:1152,subject:"제1편 가구와 목공에 설계",question:"다음 그림과 같은 투상도의 명칭은?",image:"",options:["부분 투상도","보조 투상도","국부 투상도","회전 투상도"],answer:2,explanation:""},
  {id:1153,subject:"제1편 가구와 목공에 설계",question:"투상도 표시에 대한 설명으로 틀린 것은?",image:"",options:["주투상도는 대상물의 모양, 기능을 가장 명확하게 나타낼 수 있는 면을 선정하여 그린다.","서로 관련된 그림을 배치할 때는 되도록 숨은선을 쓰지 않도록 한다.","보조 투상도는 대상물의 구멍, 홈 등 일부 모양을 확대하여 도시한 것이다.","주투상도를 보충하는 다른 투상도는 되도록 적게 한다."],answer:3,explanation:""},
  {id:1154,subject:"제1편 가구와 목공에 설계",question:"보스에서 어느 각도만큼 암이 나와 있는 물체 등을 정투상도에 의해 나타내면 제도하기 어렵다. 이때 그 부분을 투상면에 평행한 위치까지 회전시켜 실제 길이가 나타날 수 있도록 그린 투상도는?",image:"",options:["회전 투상도","국부 투상도","보조 투상도","부분 투상도"],answer:1,explanation:""},
  {id:1155,subject:"제1편 가구와 목공에 설계",question:"부품의 일부를 도시하는 것으로 충분한 경우 그 필요 부분만 도시하는 투상도는?",image:"",options:["회전 투상도","부분 투상도","국부 투상도","부분 확대도"],answer:2,explanation:""},
  {id:1156,subject:"제1편 가구와 목공에 설계",question:"국부 투상도의 설명에 해당하는 것은?",image:"",options:["대상물의 구멍, 홈 등과 같이 한 부분의 모양을 도시하는 것으로 충분한 경우의 투상도","그림의 특정 부분만을 확대하여 그린 그림","복잡한 물체를 절단하여 투상한 것","물체의 경사면에 맞서는 위치에 그린 투상도"],answer:1,explanation:""},
  {id:1157,subject:"제1편 가구와 목공에 설계",question:"부분 확대도의 도시 방법으로 틀린 것은?",image:"",options:["특정한 부분의 도형이 작아서 그 부분을 확대하여 나타내는 표현 방법이다.","확대할 부분을 굵은 실선으로 에워싸고 알파벳 대문자로 표시한다.","확대도에는 치수 기입과 표면 거칠기를 표시할 수 있다.","확대한 투상도 위에 확대를 표시하는 문자 기호와 척도를 기입한다."],answer:2,explanation:""},
  {id:1158,subject:"제1편 가구와 목공에 설계",question:"대칭형 물체를 기본 중심에서 1/2 절단하여 그림과 같이 단면한 것은?",image:"",options:["한쪽 단면도","온 단면도","부분 단면도","회전 단면도"],answer:2,explanation:""},
  {id:1159,subject:"제1편 가구와 목공에 설계",question:"한쪽 단면도는 대칭 모양의 물체를 중심선을 기준으로 얼마나 절단하여 나타내는가?",image:"",options:["전체","1/2","1/4","1/3"],answer:3,explanation:""},
  {id:1160,subject:"제1편 가구와 목공에 설계",question:"다음 그림은 어떤 단면도에 해당하는가?",image:"",options:["온 단면도","한쪽 단면도","회전 단면도","부분 단면도"],answer:4,explanation:""},
  {id:1161,subject:"제1편 가구와 목공에 설계",question:"단면도의 해칭 방법 중 틀린 것은?",image:"",options:["조립도에서 인접하는 부품의 해칭은 선의 방향 또는 각도를 바꾸어 구별한다.","절단 면적이 넓을 경우에는 외형선을 따라 적절히 해칭을 한다.","해칭면에 문자, 기호 등을 기입할 경우 해칭을 중단해서는 안 된다.","KS 규격에 제시된 재료의 단면 표시 기호를 사용할 수 있다."],answer:3,explanation:""},
  {id:1162,subject:"제1편 가구와 목공에 설계",question:"도형의 생략에 관한 설명 중 틀린 것은?",image:"",options:["대칭의 경우에는 대칭 중심선의 한쪽 도형만 그리고, 대칭 중심선의 양 끝부분에 짧은 2개의 나란한 가는 실선을 그린다.","도면을 이해할 수 있더라도 숨은선은 생략해서는 안 된다.","같은 종류, 같은 모양의 것이 다수 줄지어 있는 경우에는 지시선을 사용하여 기술할 수 있다.","물체가 긴 경우 도면의 여백을 활용하기 위해 파단선이나 지그재그선을 사용하여 투상도를 단축할 수 있다."],answer:2,explanation:""},
  {id:1163,subject:"제1편 가구와 목공에 설계",question:"기계요소 중 원칙적으로 길이 방향으로 절단하여 단면하지 않는 것으로 틀린 것은?",image:"",options:["축, 키","리벳, 핀","볼트, 작은 나사","베어링, 너트"],answer:4,explanation:""},
  {id:1164,subject:"제1편 가구와 목공에 설계",question:"단면도를 나타낼 때 긴 쪽 방향으로 절단하여 도시할 수 있는 것은?",image:"",options:["볼트, 너트, 와셔","축, 핀, 리브","리벳, 강구, 키","기어의 보스"],answer:4,explanation:""},
  {id:1165,subject:"제1편 가구와 목공에 설계",question:"치수 기입에서 (20)으로 표기된 것은 무엇을 뜻하는가?",image:"",options:["기준 치수","완성 치수","참고 치수","비례척이 아닌 치수"],answer:3,explanation:""},
  {id:1166,subject:"제1편 가구와 목공에 설계",question:"다음 중 치수 기입의 원칙에 대한 설명으로 틀린 것은?",image:"",options:["관련된 치수는 되도록 한 곳에 모아서 기입한다.","치수는 중복 기입을 할 수 있으며, 각 투상도에 고르게 치수를 기입한다.","치수는 되도록 주투상도에 집중한다.","치수는 되도록 공정마다 배열을 분리하여 기입한다."],answer:2,explanation:""},
  {id:1167,subject:"제1편 가구와 목공에 설계",question:"다음 중 치수 기입 방법에 대한 설명으로 틀린 것은?",image:"",options:["치수의 자릿수가 많을 경우에는 세 자리 숫자마다 쉼표를 붙인다.","길이 치수는 원칙적으로는 밀리미터(mm)의 단위로 기입하고, 단위 기호는 붙이지 않는다.","각도 치수를 라디안의 단위로 기입하는 경우에는 단위 기호 rad를 기입한다.","각도 치수는 일반적으로 도의 단위를 기입하고, 필요한 경우에는 분과 초를 같이 사용할 수 있다."],answer:1,explanation:""},
  {id:1168,subject:"제1편 가구와 목공에 설계",question:"치수 기입의 요소가 아닌 것은?",image:"",options:["치수선","치수 보조선","치수 숫자","해칭선"],answer:4,explanation:""},
  {id:1169,subject:"제1편 가구와 목공에 설계",question:"치수선과 치수 보조선에 대한 설명으로 틀린 것은?",image:"",options:["치수선과 치수 보조선은 가는 실선을 사용한다.","치수 보조선은 치수를 기입하는 형상에 대해 평행하게 그린다.","외형선, 중심선, 기준선 및 이들의 연장선을 치수선으로 사용하지 않는다.","치수 보조선과 치수선의 교차는 피해야 하나 불가피한 경우에는 끊김 없이 그린다."],answer:2,explanation:""},
  {id:1170,subject:"제1편 가구와 목공에 설계",question:"치수선 끝에 붙는 화살표의 길이와 너비의 비율은 어떻게 되는가?",image:"",options:["2 : 1","3 : 1","4 : 1","5 : 1"],answer:2,explanation:""},
  {id:1171,subject:"제1편 가구와 목공에 설계",question:"그림과 같이 여러 각도로 기울어진 면의 치수를 기입할 때 잘못 기입한 치수 방향은?",image:"",options:["ㄱ","ㄴ","ㄷ","ㄹ"],answer:2,explanation:""},
  {id:1172,subject:"제1편 가구와 목공에 설계",question:"치수 기입에 관한 설명으로 틀린 것은?",image:"",options:["수직 방향의 치수선에 대해서는 투상도의 오른쪽에서 읽을 수 있도록 기입한다.","치수는 치수선 중앙의 위에 약간 띄어서 쓴다.","비례척이 아닌 경우는 치수 위에 선을 긋는다.","한 도면 내의 치수는 일정한 크기로 쓴다."],answer:3,explanation:""},
  {id:1173,subject:"제1편 가구와 목공에 설계",question:"가구 제도 시 치수 기입에 대한 설명으로 옳지 않은 것은?",image:"",options:["치수는 특별히 명시하지 않는 한 마무리 치수를 표시한다.","치수는 치수선 중앙 상부에 기입하는 것이 원칙이다.","협소한 간격이 연속될 때는 지시선을 그어 치수를 기입한다.","치수의 단위는 cm를 사용함을 원칙으로 하고, 단위기호를 표시한다."],answer:4,explanation:""},
  {id:1174,subject:"제1편 가구와 목공에 설계",question:"치수 기입법에 대한 설명으로 틀린 것은?",image:"",options:["치수는 되도록 주투상도에 집중해서 지시한다.","치수선에 평행하게 기입하며 치수선 위 중앙 부분에 기입한다.","치수는 계산해서 구할 수 있도록 간단히 기입한다.","치수의 단위는 mm를 기본으로 한다."],answer:3,explanation:""},
  {id:1175,subject:"제1편 가구와 목공에 설계",question:"치수선 및 치수 보조선에 대한 설명으로 옳지 않은 것은?",image:"",options:["도면에 방해가 되지 않는 적당한 위치에 긋는다.","치수 보조선은 가는 실선으로 치수선에 직각으로 긋고, 치수선을 1520mm 넘게 연장한다.","치수 보조선은 도면에서 23mm 정도 떨어져 긋기 시작한다.","화살표 크기는 선의 굵기와 조화를 이루어야 한다."],answer:2,explanation:""},
  {id:1176,subject:"제1편 가구와 목공에 설계",question:"도면에 사용되는 기호의 예로 옳은 것은?",image:"",options:["두께 : t","45° 모따기 : B","반지름 : p","지름 : R"],answer:1,explanation:""},
  {id:1177,subject:"제1편 가구와 목공에 설계",question:"다음 투상도에 표시된 “SR”이 의미하는 것은?",image:"",options:["호의 반지름","호의 지름","구의 반지름","구의 지름"],answer:3,explanation:""},
  {id:1178,subject:"제1편 가구와 목공에 설계",question:"45° 모따기(chamfering)의 기호로 사용되는 것은?",image:"",options:["H","F","M","C"],answer:4,explanation:""},
  {id:1179,subject:"제1편 가구와 목공에 설계",question:"다음 중 치수 보조 기호의 사용 방법이 옳은 것은?",image:"",options:["φ : 구의 지름 치수 앞에 붙인다.","R : 원통의 지름 치수 앞에 붙인다.","□ : 정육면체의 변의 치수 수치 앞에 붙인다.","SR : 원형의 지름 치수 앞에 붙인다."],answer:3,explanation:""},
  {id:1180,subject:"제1편 가구와 목공에 설계",question:"호의 반지름을 기입하는 방법으로 틀린 것은 어느 것인가?",image:"",options:["1번 그림","2번 그림","3번 그림","4번 그림"],answer:4,explanation:""},
  {id:1181,subject:"제1편 가구와 목공에 설계",question:"원호의 길이를 나타내는 치수선과 치수 보조선의 도시 방법으로 옳은 것은?",image:"",options:["1번 그림","2번 그림","3번 그림","4번 그림"],answer:1,explanation:""},
  {id:1182,subject:"제1편 가구와 목공에 설계",question:"다음 중 각도 치수가 잘못 기입된 것은?",image:"",options:["1번 그림","2번 그림","3번 그림","4번 그림"],answer:1,explanation:""},
  {id:1183,subject:"제1편 가구와 목공에 설계",question:"다음 그림과 같이 테이퍼 1/200로 표시되어 있는 경우 X 부분의 치수는?",image:"",options:["89","92","96","98"],answer:4,explanation:""},
  {id:1184,subject:"제1편 가구와 목공에 설계",question:"다음 그림에서 φ20 구멍의 개수와 A 부분의 길이는?",image:"",options:["13, 1170mm","20, 1170mm","13, 1080mm","20, 1080mm"],answer:3,explanation:""},
]);
